@startuml BatchForm
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32p32.html eCTD Heading 3.2.P.3.2 Batch Formula Bundle]]" as NODES {


  node "EctdComposition32P32" as N1 {

    object "**Parent:** Composition" as obj1 {
      **Page:**
      [[StructureDefinition-ectd-composition-32p32.html]]
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }

  }
  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Page:**
      [[StructureDefinition-cmc-organization.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
    }
  }

  node "DrugProductIngredient" as NNgred {

    object "**Parent:** Ingredient" as obj10 {
      **Page:**
      [[StructureDefinition-pqcmc-dp-ingredient.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-units-of-measure.html Units Of Measure]]
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Percentage Units]]
    }
  }

  node "SubstanceDefinitionHandle" as NNS {

    object "**Parent:** SubstanceDefinition" as obj4 {
      **Page:**
      [[StructureDefinition-pqcmc-routine-drug-substance.html]]
      **ValueSets:**
      [[ValueSet-substance-classification.html Substance Classification]]
      [[ValueSet-pqcmc-quality-benchmark-terminology.html Quality Benchmark Terminology]]
    }

  }

  node "ExcipientRawNoSource" as NNSEx {

    object "**Parent:** SubstanceDefinition" as obj42 {
      **Page:**
      [[StructureDefinition-pqcmc-excipient.html]]
      **ValueSets:**
      [[ValueSet-substance-classification.html Substance Classification]]
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Sponsor Identifier Type Terminology]]
    }

  }

  node "BatchFormulaMedicinalProduct" as NN2 {

    object "**Parent:** MedicinalProductDefinition" as obj32 {
      **Page:**
      [[StructureDefinition-pqcmc-batch-formula-product.html]]
      **ValueSets:**
      [[ValueSet-spl-pharmaceutical-dosage-form-terminology.html Pharmaceutical Dosage Form Terminology]]
      [[ValueSet-spl-drug-route-of-administration-terminology.html Drug Route Of Administration Terminology]]
      [[ValueSet-pqcmc-name-part-terminology.html Name Part Terminology]]
    }
  }

  node "BatchFormula" as NN {

    object "**Parent:** ManufacturedItemDefinition" as obj3 {
      **Page:**
      [[StructureDefinition-pqcmc-product-batch-formula.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-manufactured-dose-form-terminology.html Manufactured Dose Form Terminology]]
      [[ValueSet-pqcmc-product-part-type.html Product Part Type Terminology]]
      [[ValueSet-pqcmc-batch-utilization-terminology.html Batch utilization Terminology]]
      [[ValueSet-pqcmc-non-percentage-units.html Non-Percentage Units]]
      [[ValueSet-pqcmc-percentage-units.html Percentage Units]]
      [[ValueSet-pqcmc-product-part-ingredient-physical-location.html Ingredient Location Terminology]]
      [[ValueSet-pqcmc-units-of-measure.html Units Of Measure]]

    }

    object "**Extensions**" as objExs2 {
      [[StructureDefinition-pq-overage-extension.html Overage Extension]]
      [[StructureDefinition-pq-product-batch-strength-textual-extension.html Product Batch Strength Textual Extension]]
      [[StructureDefinition-pq-additional-info-extension.html Additional Information]]
    }

    obj3 *-- objExs2
  }
  N1 -[#darkred]--> NSO
  N1 -[#darkred]-> NN2
  NNS -[#darkred]-> NSO
  NN -[#darkred]-> NSO
  NN -[#darkred]-> NNgred
  NN2 -[#darkred]-> NN
  NNgred -[#darkred]-> NNS
  NNgred -[#darkred]->NNSEx
  NNSEx -[#darkred]-> NSO
}
@enduml