@startuml BatchForm
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "eCTD Heading 3.2.P.3.2 Batch Formula Bundle" as NODES {

   object "**Bundle Reference:**" as objbun {
              [[StructureDefinition-cmc-ectd-document-sp4151.html]]
    }  

  node "EctdComposition32P32" as N1 { 
      object "**Parent:** Composition" as obj1 {
                   **Reference:**
      [[StructureDefinition-ectd-composition-32p32.html]]
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
     
}
node "CodedOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **Reference:**
      [[StructureDefinition-cmc-organization.html]]
        **ValueSets:**
        Sponsor Identifier Type Terminology 
    }
}

node "DrugProductIngredient" as NNgred { 
      object "**Parent:** Ingredient" as obj10 {
             **Reference:**
      [[StructureDefinition-pqcmc-dp-ingredient.html]]
        **ValueSets:**
        Units Of Measure    
      }      

}


node "SubstanceDefinitionHandle" as NNS { 
      object "**Parent:** SubstanceDefinition" as obj4 {
                   **Reference:**
      [[StructureDefinition-pqcmc-routine-drug-substance.html]]
                **ValueSets:**
                Substance Classification
                Quality Benchmark Terminology
      }  
}
node "BatchFormulaMedicinalProduct" as NN2 { 
      object "**Parent:** MedicinalProductDefinition" as obj32 {
                   **Reference:**
      [[StructureDefinition-pqcmc-batch-formula-product.html]]
          **ValueSets:**
           Pharmaceutical Dosage Form Terminology
          Drug Route Of Administration Terminology
          PQCMC Name Part Terminology
      }
}

node "BatchFormula" as NN { 
      object "**Parent:** ManufacturedItemDefinition" as obj3 {
         **Reference:**
      [[StructureDefinition-pqcmc-product-batch-formula.html]]
        **ValueSets:**
        Manufactured Dose Form Terminology
        Product Part Type Terminology 
        Batch utilization Terminology
        Non-Percentage Units
        Percentage Units
        Ingredient Location Terminology
        Units Of Measure

      } 
      object "**Extensions**" as objExs2 {
        Additional Information
        Product Batch Ingredient Extension
}

 obj3 *-- objExs2     
}
N1 -[#darkred]--> NSO   
N1 -[#darkred]-> NN2
NNS -[#darkred]-> NSO
NN -[#darkred]-> NSO
NN -[#darkred]-> NNgred
NN2 -[#darkred]-> NN
NNgred -[#darkred]-> NNS

}
@enduml