@startuml BatchAnalysis
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle true
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "eCTD Heading 3.2.P.5.4 and 3.2.S.4.4 Batch Analysis Bundle" as NODES {
 
   object "**Bundle Reference:**" as objbun {
              [[Structuredefinition-cmc-ectd-document-sp4151.html]]
    }       


node "DrugProductBatch" as NN { 
      object "**Parent:** Medication" as obj3 {
        **Reference:**
      [[Structuredefinition-pqcmc-drug-product-instance.html]]
        **ValueSets:**
        Drug Route Of Administration Terminology
        Pharmaceutical Dosage Form Terminology
        Expiration Date Classification Terminology
        Batch utilization Terminology
        Units Of Measure Terminology 
        Container Type Terminology
        Closure Type Terminology        
      }

      object "**Extensions**" as objExsBatch  {
                manufacturingDate
                manufacturingDateClassification
                assignedManufacturer
                expirationDateClassification
                batchUtilization
                batchQuantity
                additionalInformation
                container.extension.closureSystemDescription
                container.extension.closureType
                container.extension.lotNumber
                container.extension.quantity
                container.extension.type 
}
objExsBatch *-- obj3 
}
  node "BatchAnalysis" as N2 { 
      object "**Parent:** DiagnosticReport" as obj2 {
        **Reference:**
      [[Structuredefinition-pqcmc-batch-analysis.html]]
    }
        object "**Extensions**" as objQSEx {
        pq-quality-specification-extension
    }
    obj2 *-- objQSEx 
}

node "MfgTestSiteOrganization" as NMFG { 
      object "**Parent:** Organization" as objDP {
       **Reference:**
      [[Structuredefinition-mfg-test-site-organization.html]]
         **ValueSets:**
        Manufacturing Site Unique Identifier Type
	    GENC Country Codes
    }
}
node "DrugSubstanceBatch" as NNS { 
      object "**Parent:** Substance" as obj4 {
        **Reference:**
      [[Structuredefinition-pqcmc-drug-substance-batch.html]]
                **ValueSets:**
                Batch utilization Terminology
                Units Of Measure Terminology
                Container Type Terminology
                Closure Type Terminology
      }
  object "**Extensions**" as objExs2 {
          manufacturingDate
          manufacturingDateClassification
          assignedManufacturer
          batchUtilization
          batchQuantity
          additionalInformation
          container.extension.closureSystemDescription
          container.extension.closureType
          container.extension.lotNumber
          container.extension.quantity
          container.extension.type
    }

    objExs2 *-- obj4   
}

node "ResultObservation" as NNOBS { 
      object "**Parent:** Observation" as observ3 {
        **Reference:**
      [[Structuredefinition-pq-result-observation.html]]
        **ValueSets:**
        Conformance Criteria Terminology
        Units Of Measure Terminology    
      }
      object "**Extensions**" as objExsObserv  {
            pq-pullDate-extension
            pq-interpretation-code-extension
            pq-replicate-extension
    }
        objExsObserv *-- observ3 
}

node "MultipleReplicatesResultObservation" as NNstage { 
      object "**Parent:** Observation" as observS {
        **Reference:**
      [[Structuredefinition-pq-additional-stage-result-observation.html]]
        **ValueSets:**
 PqcmcConformanceCriteriaTerminology
 PqcmcUnitsMeasureTerminology
      }
      object "**Extensions**" as objExsStageObs  {
            pq-pullDate-extension
            pq-interpretation-code-extension
            pq-replicate-extension
     }  
        objExsStageObs *-- observS
}

node "EctdCompositionSP4151" as N1 { 
      object "**Parent:** Composition" as obj1 {
        **Reference:**
      [[Structuredefinition-ectd-composition-sp4454.html]]
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
}
node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **Reference:**
      [[Structuredefinition-cmc-sponsor-organization.html]]
        **ValueSets:**
        GENC Country Codes
    }
}
 diamond CH

N1 -[#darkred]-> CH
N1 -[#darkred]-> N2
N1 -[#darkred]-> NSO
CH -[#green]-> NNS
CH -[#green]-> NN
NNS -[#darkred]-> NMFG
NN -[#darkred]-> NMFG
N2 -[#darkred]-> CH
N2 -[#darkred]-> NMFG
N2 -[#darkred]-> NNOBS
NNOBS -[#darkred]-> NMFG
NNOBS -[#darkred]-> NNstage
NNstage -[#darkred]-> NMFG
}
@enduml