@startuml BatchForm
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "eCTD Heading 3.2.P.3.2 Batch Formula Bundle" as NODES {

   object "**Bundle Reference:**" as objbun {
              [[StructureDefinition-cmc-ectd-document-sp4151.html]]
    }  

 
node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **Reference:**
      [[StructureDefinition-cmc-sponsor-organization.html]]
        **ValueSets:**
        Sponsor Identifier Type Terminology 
    }
}

node "DrugProductIngredient" as NNgred { 
      object "**Parent:** Ingredient" as obj10 {
             **Reference:**
      [[StructureDefinition-pqcmc-dp-ingredient.html]]
        **ValueSets:**
        Units of Measure Terminology    
      }      

}
 node "EctdComposition32P32" as N1 { 
      object "**Parent:** Composition" as obj1 {
                   **Reference:**
      [[StructureDefinition-ectd-composition-32p32.html]]
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
     
}
node "MfgTestSiteOrganization" as NMFG { 
      object "**Parent:** Organization" as objDP {
                   **Reference:**
      [[StructureDefinition-cmc-organization.html]]
         **ValueSets:**
        Testing Site and Organization Identifier Type Terminology
    }
}

node "RoutineSubstanceDefinition" as NNS { 
      object "**Parent:** SubstanceDefinition" as obj4 {
                   **Reference:**
      [[StructureDefinition-pqcmc-routine-drug-substance.html]]
                **ValueSets:**
                Substance Classification
                Quality Benchmark Terminology
      }  
}
node "BatchFormulaMedicinalProduct" as NN2 { 
      object "**Parent:** MedicinalProductDefinition" as obj32 {
                   **Reference:**
      [[StructureDefinition-pqcmc-batch-formula-product.html]]
          
      }
}

node "BatchFormula" as NN { 
      object "**Parent:** ManufacturedItemDefinition" as obj3 {
         **Reference:**
      [[StructureDefinition-pqcmc-product-batch-formula.html]]
        **ValueSets:**
        Product Part Ingredient Physical Location value set        
        Batch utilization Terminology
        Units Of Measure Terminology
      } 
      object "**Extensions**" as objExs2 {
        Additional Information
        Product Batch Ingredient Extension
}

 obj3 *-- objExs2     
}

NN -[#darkred]-> NMFG
NN -[#darkred]-> NNgred
NN2 -[#darkred]-> NN
N1 -[#darkred]-> NN2
N1 -[#darkred]-> NSO        
NNS -[#darkred]-> NMFG
NNgred -[#darkred]-> NNS

}
@enduml