@startuml
allowmixing
'Mixed model of use case and object
package "eCTD Heading 3.2.P.5.5 Characterization of Impurities Bundle" as NODES {

node "EctdComposition32P55" as N1 { 
      object "**Parent:** Composition" as obj1 {
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
}
 node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **ValueSets:**
        GENC Country Codes
    }
} 
  
  node "DrugProductwithImpurites" as NN { 
      object "**Parent:** MedicationDefinition" as obj3 {      
      }
  }

node "ImpuritySubstance" as N6 { 
      object "**Parent:** SubstanceDefinition" as obj2 {
      **ValueSets:**
      EVMPDSubstanceClassification
      PqcmcImpurityClassificationTerminology
      Chemical Structure Data File Type Terminology
    }
     
}

N1 --> NSO   
NN --> N6
N1 --> NN 
}
@enduml

