@startuml CharacImprity
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32p55.html eCTD Heading 3.2.P.5.5 Characterisation of Impurities Bundle]]" as NODES {


  node "EctdComposition32P55" as N1 {

    object "**Parent:** Composition" as obj1 {
      **Page:**
      [[StructureDefinition-ectd-composition-32p55.html]]
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }
  }
  node "GraphicReference" as NB64 {

    object "**Parent Profile:** Base64DocumentReference"  as obj64 {
      **Page:**
      [[StructureDefinition-pqcmc-graphic-reference.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-graphical-file-types.html Graphical File Types]]
    }
  }
  node "StructureReference" as NBstruc {

    object "**Parent Profile:** Base64DocumentReference"  as objb64 {
      **Page:**
      [[StructureDefinition-pqcmc-structure-reference.html]]
       **ValueSets:**
      [[ValueSet-pqcmc-structure-data-types.html Structure Data Types]] 
    }
  }

  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Page:**
      [[StructureDefinition-cmc-organization.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
    }
  }

  node "DrugProductwithImpurities" as NN {

    object "**Parent:** MedicinalProductDefinition" as obj3 {

      **Page:**
      [[StructureDefinition-pqcmc-drug-product-with-impurities.html]]
      **ValueSets:**
      [[ValueSet-spl-pharmaceutical-dosage-form-terminology.html Pharmaceutical Dosage Form Terminology]]
      [[ValueSet-spl-drug-route-of-administration-terminology.html Drug Route Of Administration Terminology]]
      [[ValueSet-pqcmc-name-part-terminology.html Name Part Terminology]]
    }
  }

  node "ImpuritySubstance" as N6 {

    object "**Parent:** SubstanceDefinition" as obj2 {
      **Page:**
      [[StructureDefinition-pqcmc-drug-product-substance-impurity.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-impurity-classification-terminology.html Impurity Classification Terminology]]
      [[ValueSet-pqcmc-analytical-instrument-data-types.html Analytical Instrument Data File Types]]
    }
  }
  N1 -[#darkred]-> NSO
  NN -[#darkred]-> N6
  N1 -[#darkred]-> NN
  N6 -[#darkred]-> NB64
  N6 -[#darkred]-> NBstruc

}
@enduml
