@startuml
allowmixing
'Mixed model of use case and object
package "eCTD Heading 3.2.P.7 Container Closure System Bundle" as NODES {
   
  node "EctdComposition32P7" as N1 { 
      object "**Parent:** Composition" as obj1 {
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }   
}
node "DrugProductContainerClosure" as N21 { 
      object "**Parent:** DrugProduct Profile" as obj22 {
        **ValueSets:**
        Container Type Terminology
        Closure Type Terminology
    }
    object "**Extensions**" as objEx {
        mdpcontainerClosure
    }
    obj22 <|-- objEx
}

node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **ValueSets:**
        GENC Country Codes
    }
}
}

N1 --> N21
N1 --> NSO

@enduml