@startuml legend
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "Bundle" as NODES {
  node "A Profile on a resource" as Nameprofile {
    object "**Parent:** Name of Resource or 'Profile' name if parent is a profile" as objcs {
      **ValueSets:**
      Terminology 1
      Terminology 2
      Terminology 3
    }
  }

  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Page:**
      [[StructureDefinition-cmc-organization.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
    }
  }

  diamond CH

  node "Example Profile" as NN {

    object "**Parent:** a Resource" as obj3 {
      **ValueSets:**
      Terminology 1
      Terminology 2
      Terminology 3
      ...
    }
    object "**Extensions**" as objExs {
      extension 1
      extension 2
      ...
    }
    obj3 *-- objExs : Resource supported with extensions

  }

  node "Profile on a resource.  All eCTD bundles have a composition profile" as N1 {

    object "**Parent:** Composition" as obj1 {
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }

  }

  node "Another Profile on a resource" as NN3 {

    object "**Parent:** a Resource" as obj33 {
      **ValueSets:**
      Terminology 1
      Terminology 2
      ...
    }
  }

  N1 -[#darkred]-> NSO
  NN -[#darkred]-> CH : A profile can have a choice of reference profiles
  CH -[#green]-> Nameprofile
  CH -[#green]-> NN3
  N1 -[#darkred]-> NN :  Relationship(s) between profiles to referenced profile.  
}
@enduml