@startuml
title Stability Data Resource Relationships

class Medication {
  +identifier
}

class StabilityStudy {
  +title
  +status
  +subject
  +partOf
  +arm
  +objective
}

class StabilityEvidence {
  +exposureBackground
  +variableDefinition
  +statistic
}

class IntervalReportDiagnosticReport {
  +code
  +effectiveDateTime
  +subject
}

class ResultObservation {
  +AbsentReason
  +interpretation
  +Conformance to Criteria
}

class StabilityAssessment {
  +artifact
  +content
}


Profile: StabilityStudy
Parent: ResearchStudy
Id: pq-stability-study
Title: "Stability Study"


Profile: StabilitySubStudy
Parent: ResearchStudy
Id: pq-stability-sub-study
Title: "Stability Sub-Study"

* insert PQReference(partOf)
* partOf only Reference(StabilityStudy or StabilitySubStudy)
* insert PQReference(result)
* result only Reference(StabilityStudyIntervalReport)


Profile: StabilityStudyIntervalReport
Parent: DiagnosticReport
Id: pqcmc-stability-study-interval-report
Title: "Stability Study Interval Report"

* insert PQReference(subject)
* subject only Reference(DrugProductBatch or DrugSubstanceBatch)
* insert PQReference(performer)
* performer only Reference(CodedOrganization)
* insert PQReference(result)
* result only Reference(ResultObservation)


StabilityStudy  --> MedicationDefinition : subject
StabilitySubStudy --> StabilityStudy : partOf
StabilityStudy <-- IntervalReportDiagnosticReport : partOf
StabilityTestResult --> Medication : subject
StabilityEvidence --> StabilityStudy : exposureBackground
StabilityEvidence --> Medication : observed
StabilityAssessment --> StabilityEvidence : artifact
StabilityAssessment --> StabilityStudy : artifact
StabilityAssessment --> Medication : artifact

@enduml