@startuml ProdDesComp
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32p10.html eCTD Heading 3.2.P.1 Bundle]]" as NODES {
  node "ContainerClosure" as N21 {

    object "**Parent:** PackagedProductDefinition" as obj22 {
      **Page:**
      [[StructureDefinition-ContainerClosure.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-container-type-terminology.html Container Type Terminology]]
      [[ValueSet-pqcmc-closure-type-terminology.html Closure Type Terminology]]
    }
  }

  node "DrugProductDescription" as N2 {

    object "**Parent:** MedicinalProductDefinition" as obj2 {
      **Page:**
      [[StructureDefinition-pqcmc-drug-product-description.html]]
      **ValueSets:**
      [[ValueSet-spl-pharmaceutical-dosage-form-terminology.html Pharmaceutical Dosage Form Terminology]]
      [[ValueSet-spl-drug-route-of-administration-terminology.html Drug Route Of Administration Terminology]]
      [[ValueSet-pqcmc-name-part-terminology.html PQCMC Name Part Terminology]]
    }
  }

  node "DrugProductHandle" as N2handle {

    object "**Parent:** MedicinalProductDefinition" as objcross {
      **Page:**
      [[StructureDefinition-pqcmc-drug-product-handle.html]]
      **ValueSets:**
      [[ValueSet-spl-drug-route-of-administration-terminology.html Drug Route Of Administration Terminology]]
      [[ValueSet-spl-pharmaceutical-dosage-form-terminology.html Pharmaceutical Dosage Form Terminology]]
      [[ValueSet-pqcmc-name-part-terminology.html PQCMC Name Part Terminology]]
    }
  }

  node "FinishedProduct"as MID {
    object "**Parent:** ManufacturedItemDefinition" as objMID {

      **Page:**
      [[StructureDefinition-pqcmc-product-part.html]]
      **ValueSets:**
      [[ValueSet-capsule-classification-category.html Capsule Classification Category]]
      [[ValueSet-pqcmc-coating-purpose.html Coating Purpose]]
      [[ValueSet-pqcmc-drug-product-component-function-category-terminology.html Drug Product Component Function Category Terminology]]
      [[ValueSet-pqcmc-excipient-function-terminology.html Excipient Function Terminology]]
      [[ValueSet-pqcmc-manufactured-dose-form-terminology.html Manufactured Dose Form Terminology]]
      [[ValueSet-pqcmc-non-percentage-units.html Non Percentage Units]]
      [[ValueSet-pqcmc-percentage-units.html Percentage Units]]
      [[ValueSet-pqcmc-product-part-ingredient-physical-location.html Product Part Ingredient Physical Location]]
      [[ValueSet-pqcmc-product-part-type.html Product Part Type]]
      [[ValueSet-pqcmc-quality-benchmark-terminology.html Quality Benchmark Terminology]]
      [[ValueSet-pqcmc-release-mechanism.html Release Mechanism]]
      [[ValueSet-pqcmc-release-profile.html Release Profile]]
      [[ValueSet-pqcmc-strength-type-terminology.html Strength Type Terminology]]
      [[ValueSet-pqcmc-units-of-measure.html Units Of Measure]]
    }
    object "**Extensions**" as objMIDExs {
      [[StructureDefinition-pq-amount-ratio.html Amount Ratio]]
    }
    objMID *-- objMIDExs
  }
  node "DrugProductComponent" as NN {

    object "**Parent:** Ingredient" as obj3 {
      **Page:**
      [[StructureDefinition-pqcmc-component.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-drug-product-component-function-category-terminology.html Drug Product Component Function Category Terminology]]
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Non-Percentage Units]]
      [[ValueSet-pqcmc-percentage-units.html Percentage Units]]
    }
    object "**Extensions**" as objExs {
      [[StructureDefinition-strength-extension.html Strength Extension]]
    }
    obj3 *-- objExs
  }

  node "ComponentSubstance" as NCS {

    object "**Parent:** SubstanceDefinition" as objSubDef {
      **Page:**
      [[StructureDefinition-pqcmc-component-substance.html]]
      **ValueSets:**
      [[ValueSet-substance-classification.html Substance Classification]]
      [[ValueSet-pqcmc-quality-benchmark-terminology.html Quality Benchmark Terminology]]
      [[ValueSet-pqcmc-source-type-terminology.html Source Type Terminology]]
      [[ValueSet-pqcmc-genc-and-iso-intersect.html GENC and ISO 3166 Intersection]]
      [[ValueSet-pqcmc-substance-name-type.html Substance Name Type]]
    }
  }

    node "GraphicReference" as NB64 {

    object "**Parent Profile:** Base64DocumentReference"  as obj64 {
      **Page:**
      [[StructureDefinition-pqcmc-graphic-reference.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-graphical-file-types.html Graphical File Types]]
    }
  }

  node "StructureReference" as NBstruc {

    object "**Parent Profile:** Base64DocumentReference"  as objb64 {
      **Page:**
      [[StructureDefinition-pqcmc-structure-reference.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-structure-data-types.html Structure Data Types]]
    }
  }
  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Page:**
      [[StructureDefinition-cmc-organization.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
      
    }
  }

  node "EctdComposition32P10" as N1 {

    object "**Parent:** Composition" as obj1 {
      **Page:**
      [[StructureDefinition-ectd-composition-32p10.html]]
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }

  }

  N1 -[#darkred]--> N2
  N1 -[#darkred]--> MID
  N1 -[#darkred]--> NSO
  N1 -[#darkred]--> N21
  N2 -[#darkred]--> N2handle : Only when there is a Co-Packaged Product
  N21 -[#darkred]--> NB64
  N21 -[#darkred]--> N2
  MID -[#darkred]--> NN
  NCS -[#darkred]--> NSO
  NN -[#darkred]--> NCS
  NCS -[#darkred]--> NB64
  NCS -[#darkred]--> NBstruc
}
@enduml