@startuml StabilitySummary
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "eCTD Heading 3.2.S.7.1 and 3.2.P.8.1 Stability Summary Bundle" as NODES {
      object "**Bundle Reference:**" as objbun {
            [[StructureDefinition-cmc-ectd-document-sp7181.html]]
      }

      node "DrugProductHandle" as NN {

            object "**Parent:** MedicinalProductDefinition" as obj3 {
                  **Reference:**
                  [[StructureDefinition-pqcmc-drug-product-handle.html]]
                  **ValueSets:**
                  Drug Route Of Administration Terminology
                  Pharmaceutical Dosage Form Terminology
                  Name Part Terminology
            }
      }
      diamond CH

      node "SubstanceDefinitionHandle for API" as NNS {

            object "**Parent Profile:** DrugSubstance" as obj4 {
                  **Reference:**
                  [[StructureDefinition-pqcmc-routine-drug-substance.html]]
                  **ValueSets:**
                  Substance Classification
                  Quality Benchmark Terminology
            }
      }

      node "MfgTestSiteOrganization" as NMFG {

            object "**Parent:** Organization" as objDP {
                  **Reference:**
                  [[StructureDefinition-cmc-organization.html]]
                  **ValueSets:**
                  Testing Site and Organization Identifier Type Terminology
            }
      }

      node "StabilitySummary" as NMain {

            object "**Parent:** PlanDefinition" as objMain {
                  **Reference:**
                  [[StructureDefinition-pqcmc-stability-summary.html]]
                  **ValueSets:**
                  Units Of Measure
                  Storage Conditions Terminology
            }

            object "**Extensions**" as objExs2 {
                  Additional Information
            }

            objMain *-- objExs2
      }

      node "EctdCompositionSP7181" as N1 {

            object "**Parent:** Composition" as obj1 {
                  **Reference:**
                  [[StructureDefinition-ectd-composition-sp7181.html]]
                  **ValueSets:**
                  Code system PQCMC Comp Section Types
            }
      }
      node "CodedOrganization" as NSO {

            object "**Parent:** Organization" as objAu {
                  **Reference:**
                  [[StructureDefinition-cmc-organization.html]]
                  **ValueSets:**
                  Testing Site and Organization Identifier Type Terminology
            }
      }

      CH -[#green]-> NN
      CH -[#green]-> NNS
      N1 -[#darkred]-> CH
      N1 -[#darkred]-> NSO
      NN -[#darkred]-> NMFG
      NNS -[#darkred]-> NMFG
      N1 -[#darkred]-> NMain


}
@enduml