@startuml SubstanceImpurity
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32s3.html 3.2.S.3 eCTD Heading Characterisation Bundle]]" as NODES {

  node "EctdComposition32S3" as N1 {

    object "**Parent:** Composition" as obj1 {
      **Reference:**
      [[StructureDefinition-ectd-composition-32s3.html]]
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }
  }
  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Reference:**
      [[StructureDefinition-cmc-organization.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
    }
  }

  node "DrugSubstanceCharacterisation" as NN {

    object "**Parent:** SubstanceDefintion" as obj3 {

      **Reference:**
      [[StructureDefinition-pqcmc-drug-substance-characterisation.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-chemical-structure-datafile-type-terminology.html Chemical Structure Data File Type Terminology]]
      [[ValueSet-pqcmc-representation-types.html Representation Types]]
      [[ValueSet-substance-classification.html Substance Classification]]
      [[ValueSet-pqcmc-analytical-instrument-data-types.html Analytical Instrument Data File Types]]
    }
  }

  node "ImpuritySubstance" as N6 {

    object "**Parent:** SubstanceDefinition" as obj2 {
      **Reference:**
      [[StructureDefinition-pqcmc-drug-product-substance-impurity.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-impurity-classification-terminology.html Impurity Classification Terminology]]
      [[ValueSet-pqcmc-analytical-instrument-data-types.html Analytical Instrument Data File Types]]
    }
  }
  node "GraphicReference" as NB64 {

    object "**Parent Profile:** Base64DocumentReference"  as obj64 {
      **Reference:**
      [[StructureDefinition-pqcmc-graphic-reference.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-graphical-file-types.html Graphical File Types]]
    }
  }
  node "StructureReference" as NBstruc {

    object "**Parent Profile:** Base64DocumentReference"  as objb64 {
      **Reference:**
      [[StructureDefinition-pqcmc-structure-reference.html]]
    }
  }

  N1 -[#darkred]-> NSO
  NN -[#darkred]-> N6
  N1 -[#darkred]-> NN
  N6 -[#darkred]-> NB64
  N6 -[#darkred]-> NBstruc
}
@enduml