@startuml SubstanceContainer
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32s60.html eCTD Heading 3.2.S.6 Container Closure System Bundle]]" as NODES {



  node "EctdComposition32S60" as N1 {

    object "**Parent:** Composition" as obj1 {
      **Page:**
      [[StructureDefinition-ectd-composition-32s60.html]]
      **ValueSets:**
      [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
    }

  }
  node "SubstanceContainerClosure" as N21 {

    object "**Parent:** DrugSubstance Profile" as obj22 {
      **Page:**
      [[StructureDefinition-pqcmc-drug-substance-container-closure.html]]
      **ValueSets:**
      [[ValueSet-pqcmc-container-type-terminology.html Container Type Terminology]]
      [[ValueSet-pqcmc-closure-type-terminology.html Closure Type Terminology]]
    }
    object "**Extensions**" as objEx {
      containerClosure
    }
    obj22 <|-- objEx
  }
  node "Base64DocumentReference" as NB64 {

    object "**Parent:** DocumentReference"  as obj64 {

      **Page:**
      [[StructureDefinition-cmc-document-reference.html]]
    }

  }
  node "CodedOrganization" as NSO {

    object "**Parent:** Organization" as objAu {
      **Page:**
      [[StructureDefinition-cmc-organization.html]]

    }
  }
}

N1 -[#darkred]-> N21
N1 -[#darkred]-> NSO
objEx -[#darkred]-> NB64
@enduml