@startuml SubstanceControlMat
allowmixing
'Mixed model of use case and object
skinparam svgDimensionStyle false
skinparam ObjectBackgroundColor LightYellow
skinparam ObjectBorderColor #A80036
skinparam activityDiamondBorderColor #A80036
skinparam activityDiamondBackgroundColor lawnGreen
skinparam ClassBorderThickness 4

package "[[StructureDefinition-cmc-ectd-document-32s23.html eCTD Heading 3.2.S.2.3 Control of Materials Bundle]]" as NODES {

    node "QualitySpecification" as N2 {

        object "**Parent:** PlanDefinition" as obj2 {
            **Reference:**
            [[StructureDefinition-pqcmc-quality-specification.html]]
            **ValueSets**
            [[ValueSet-pqcmc-specification-status-terminology.html Specification Status Terminology]]
            [[ValueSet-pqcmc-test-category-terminology.html Test Category Terminology]]
            [[ValueSet-pqcmc-test-method-origin-terminology.html Test Method Origin Terminology]]
            [[ValueSet-pqcmc-test-usage-terminology.html Test Usage Terminology]]
            [[ValueSet-pqcmc-units-of-measure.html Units Of Measure]]
        }
        object "**Extensions**" as objQSEx {
            [[StructureDefinition-pq-additional-info-extension.html Additional Information]]
            [[StructureDefinition-pq-hierarchical-level-extension.html Hierarchical Level]]
            [[StructureDefinition-pq-specification-status-extension.html Specification Status]]
            [[StructureDefinition-pq-target-range.html Target Range]]
        }
        obj2 <|-- objQSEx
    }
    node "EctdComposition32S23" as N1 {

        object "**Parent:** Composition" as obj1 {
            **Reference:**
            [[StructureDefinition-ectd-composition-32s23.html]]
            **ValueSets:**
            [[ValueSet-cmc-comp-section-types-vs.html Code system PQCMC Comp Section Types]]
        }
    }

    node "ExcipientRaw" as N21 {

        object "**Parent:** SubstanceDefinition" as obj22 {
            **Reference:**
            [[StructureDefinition-pqcmc-excipient.html]]
            **ValueSets:**
            [[ValueSet-pqcmc-source-type-terminology.html Source Type Terminology]]
            [[ValueSet-substance-classification.html Substance Classification]]
            [[ValueSet-pqcmc-quality-benchmark-terminology.html Quality Benchmark Terminology]]
        }
    }
    node "CodedOrganization" as NSO {

        object "**Parent:** Organization" as objAu {
            **Reference:**
            [[StructureDefinition-cmc-organization.html]]
            **ValueSets:**
            [[ValueSet-pqcmc-org-identifier-type-terminology.html Organization-Site Identifier Terminology]]
        }
    }

    node "SubstanceDefinitionHandle" as NN {

        object "**Parent:** SubstanceDefinition" as obj3 {
            **Reference:**
            [[StructureDefinition-pqcmc-routine-drug-substance.html]]
            **ValueSets:**
            [[ValueSet-pqcmc-org-identifier-type-terminology.html Sponsor Identifier Type Terminology]]
        }
    }

    N1 -[#darkred]--> N2
    N2 -[#darkred]-> N21
    N1 -[#darkred]--> NSO
    N1 -[#darkred]--> NN
    N21 -[#darkred]-> NSO
}
@enduml