@startuml
allowmixing
'Mixed model of use case and object
package "eCTD Folder 3.2.S.2.3 Control of Materials Bundle" as NODES {
  
  node "EctdComposition32S23" as N1 { 
      object "**Parent:** Composition" as obj1 {
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
     
}

 node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
        **ValueSets:**
        GENC Country Codes
    }
} 
  node "ExcipientRaw" as N21 { 
      object "**Parent:** SubstanceDefinition" as obj22 {
        **ValueSets:**
          GENC Country Codes
          Source Type Terminology
    }
}
node "MfgTestSiteOrganization" as N21mfg { 
    object "**Parent:** Organization" as objTS  {
        **ValueSets:**
         Manufacturing Site Unique Identifier Type
         GENC Country Codes
    }
}

 node "QualitySpecification" as N2 { 
      object "**Parent:** PlanDefinition" as obj2 {
        **ValueSets**
        PqActionRelationTypes
        PqcmcInterpretationCodeTerminology
        PqcmcSpecificationStatusTerminology
        PqcmcSpecificationTypeTerminology
        PqcmcTestCategoryTerminology
        PqcmcTestMethodOriginTerminology
        PqcmcTestUsageTerminology
        PqcmcUnitsMeasureTerminology
    }
        object "**Extensions**" as objQSEx {
        AdditionalInformationExtension
        InterpretationCodeExtension
        SpecificationStatusExtension
        SpecificationTypeExtension
        TestMethodOriginExtension
        TestOrderExtension
        RRTExtension
    }
    obj2 <|-- objQSEx
}

N1 --> N21
N2 --> N21
N1 --> NSO
N21 --> N21mfg
}
@enduml