@startuml
allowmixing
'Mixed model of use case and object
package "3.2.S.3.0 eCTD Heading Characterisation Bundle" as NODES {
  
node "EctdComposition32S30" as N1 { 
      object "**Parent:** Composition" as obj1 {
          **Reference:**
      [[StructureDefinition-cmc-ectd-document-32s30.html]]
      **ValueSets:**
  Code system PQCMC Comp Section Types
    }
}
 node "SponsorOrganization" as NSO { 
      object "**Parent:** Organization" as objAu {
    **Reference:**
      [[StructureDefinition-cmc-sponsor-organization.html]]
        **ValueSets:**
        GENC Country Codes
    }
} 
  
  node "DrugSubstance" as NN { 
      object "**Parent:** SubstanceDefintion" as obj3 { 
  **Reference:**
      [[StructureDefinition-pqcmc-drug-substance.html]]
        **ValueSets:**
      Chemical Structure Data File Type Terminology  
      }
  }

node "DrugSubstanceImpurities" as N6 { 
      object "**Parent:** DrugSubstance" as obj2 {
     **Reference:**
      [[StructureDefinition-pqcmc-drug-substance-impurity.html]]   
      **ValueSets:**
      PqcmcImpurityClassificationTerminology
      Chemical Structure Data File Type Terminology  
    }   
}

N1 --> NSO   
NN --> N6
N1 --> NN 
}
@enduml