Alias: $data-absent-reason = http://hl7.org/fhir/StructureDefinition/data-absent-reason
//Alias: $NCIT = http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl 2.16.840.1.113883.3.26.1.1
Alias: $NCIT = http://hl7.org/fhir/us/pq-cmc-fda/CodeSystem/cmc-ncit-dummy //temp until server issue resolved
Alias: $UNII = https://fdasis.nlm.nih.gov ///urn:oid:2.16.840.1.113883.4.9
Alias: $UNIPROT = https://www.uniprot.org
Alias: $CAS = urn:oid:1.3.6.1.4.1.5193
//Alias: $UCUM = http://unitsofmeasure.org  // replaced with NCIT
Alias: $DUNS = urn:oid:1.3.6.1.4.1.519.1
Alias: $FEINumber = urn:oid:2.16.840.1.113883.4.82
Alias: $ART = http://hl7.org/fhir/action-relationship-type
Alias: $FEI = https://www.fda.gov/drugs/drug-approvals-and-databases/drug-establishments-current-registration-site
// Alias: $EMAIDMP = https://www.ema.europa.eu
Alias: $Country = urn:iso:std:iso:3166
Alias: $IDsys = urn:ietf:rfc:3986
Alias: $SubstanceRelationshipType = http://hl7.org/fhir/substance-relationship-type
Alias: $IDENTIFIER-TYPE = http://hl7.org/fhir/ValueSet/identifier-type
Alias: $NamePartType = http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2
Alias: $SectionTypes = http://hl7.org/fhir/us/pq-cmc-fda/CodeSystem/pqcmc-comp-section-types
Alias: $DOCREF = http://hl7.org/fhir/document-reference-status 
Alias: $NameType = http://hl7.org/fhir/us/pq-cmc-fda/CodeSystem/cmc-product-name-types
Alias: $ActRelationType = http://hl7.org/fhir/action-relationship-type
Alias: $ActSelection = http://hl7.org/fhir/action-selection-behavior
Alias: $TestCats = http://hl7.org/fhir/us/pq-cmc-fda/CodeSystem/pqcmc-test-category-codes
Alias: $PubStatus = http://hl7.org/fhir/publication-status#draft 
