Alias: $data-absent-reason = http://hl7.org/fhir/StructureDefinition/data-absent-reason
Alias: $NCIT = http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl
Alias: $UNII = https://gsrs.ncats.nih.gov  ///urn:oid:2.16.840.1.113883.4.9
Alias: $CAS = urn:oid:1.3.6.1.4.1.5193
Alias: $UCUM = http://unitsofmeasure.org
Alias: $DUNS  = urn:oid:1.3.6.1.4.1.519.1
Alias: $FEINumber = urn:oid:2.16.840.1.113883.4.82
Alias: $ART = http://hl7.org/fhir/action-relationship-type
Alias: $FEI = https://www.fda.gov/drugs/drug-approvals-and-databases/drug-establishments-current-registration-site
//Alias: $SectionTypes = http://hl7.org/fhir/us/pq-cmc/code-system/SectionType
//Alias: $NameTypes = http://hl7.org/fhir/us/pq-cmc/code-system/NameType
Alias: $EMAIDMP = https://www.ema.europa.eu
Alias: $GENC = https://nsgreg.nga.mil
Alias: $IDsys = urn:ietf:rfc:3986
Alias: $SectionTypes = http://hl7.org/fhir/us/pq-cmc/codesystem/SectionType
Alias: $PQTC = http://hl7.org/fhir/us/pq-cmc/codesystem/PqcmcTestCategoryCodes