CodeSystem: Temporary
Id: temporary
Title: "PQ-CMC-FDA Temporary Codes"
Description: """Codes are temporarily defined as part of the PQ-CMC-FDA implementation guide. """
* ^caseSensitive = true
* ^status = #active
* ^hierarchyMeaning = #is-a

// test category (hierarchical)
* #C60819 "Assay" "A qualitative or quantitative analysis performed to determine the amount of a particular constituent in a sample or the biological or pharmacological properties of a drug."
* #C60819 #C204845 "Active Ingredient Content" "Tests that verify the content and potency of a pharmaceutical substance that is intended to have an effect in the diagnosis, cure, mitigation, treatment, or prevention of disease, or to impact a structure or function of the body."
* #C60819 #C205001 "Adventitious Agents (Safety)" "In vitro and in vivo assays for detection of unintended agents such as viral, bacterial, fungal agents which have undesirable adverse impact on patient's health."
* #C60819 #C81183 "Amino Acid Content" "Methodology used to determine the amino acid composition or content of proteins, peptides, and other pharmaceutical preparations."
* #C60819 #C205003 "Bioburden" "Test that screens for aerobic mesophilic bacteria and fungi."
* #C60819 #C205007 "Counterion Content" "Tests that measure the secondary ion of a drug salt."
* #C60819 #C205015 "Excipient" "Testing of the amount of material other than the active or adjuvant."
* #C60819 #C205018 "Host Cell DNA" "Measurement of DNA that comes from cell substrate used to make the viral particles."
* #C60819 #C205020 "In Vitro or In Vivo Test for Viral Contaminants" "Test used to measure viral contamination both by in vitro and in vivo assays"
* #C60819 #C205028 "Percent Conjugate" "Test to determine the percentage of total protein that functions in interaction with other (non-polypeptide) chemical groups attached by covalent bonding."
* #C60819 #C62352 "Purity" "Testing methods to identify actives and indirectly measure impurities that may be present in a medicine. Examples of analytical procedures for this test subcategory include SDS-PAGE and HPLC."
* #C60819 #C171277 "Nucleic Acid Content" "Tests designed to reveal the presence of a particular nucleic acid from a test sample."
* #C60819 #C205038 "Solvate Content" "Identification of hydrates or solvates by the assay of water of crystallization or solvent found in the crystal."
* #C60819 #C64858 "Total Protein" "Test to determine total protein concentration in the product."
* #C60819 #C205006 "Cell and Gene Therapy Product Characterization Assay" "Tests to determine Cell and Gene therapy product properties. Examples: Viability, Cell number, Morphology, Cell surface markers, Secreted molecules, Gene expression, Genetic stability, percent recovery, gene expression, cell surface marker expression, proliferation capacity, total cell number, cell morphology, cell distribution in scaffold, total volume of scaffold, cellular pattern, vector genome concentration, vector infectious titer assay, replication competence assay, DNA homogeneity, transduction efficiency, vector genome concentration, vector infectious titer assay, Replication competence assay."
* #C134249 "Container Closure Integrity" "Tests for the adequacy of pharmaceutical packaging and container closures."
* #C134250 "Uniformity" "Tests to ensure the consistency of the API in the formulation. Test may be done as an IPC, release, or stability test."
* #C134250 #C205004 "Blend Uniformity" "Test to ensure the adequacy of the mixing of active pharmaceutical ingredients (APIs) with other components of the drug product."
* #C134250 #C205019 "IPC Content Uniformity" "In-Process Control (IPC) tests of the variability of individual dosage units during manufacture as informed by ASTM E2810."
* #C134250 #C134115 "Uniformity of Dosage Unit" "Tests of the variability each of the dosage unit's dispensed dose."
* #C134250 #C205050 "Uniformity in Containers" "Content Uniformity based for multi-use containers, tubes, and jars. The consistency of the active ingredient throughout multi-use containers such as tubes, and jars of semi-solids."
* #C133961 "Deliverable Volume/Fill Volume" "Tests designed to provide assurance that oral liquids will, when transferred from the original container, deliver the volume of dosage form that is declared on the label of the article."
* #C205026 "Organoleptic" "Evaluation via the senses—including taste, sight, smell, and touch."
* #C205026 #C138990 "Description/Appearance" "Tests using visual inspection to assess the physical state and color of the drug substance or product."
* #C205026 #C139027 "Odor" "Testing via the sense of smell."
* #C205026 #C134262 "Color of Solution" "The use of visual perception to indicate of purity and/or a means to identify contamination."
* #C205026 #C134261 "Clarity of Solution" "Measurement of the turbidity of the solution or qualitative or quantitative measurement of degree of opalescence of a solution, including instrumental measurement of the light reflected by the solution."
* #C138993 "Identification" "Tests that establish the characteristic and uniqueness of the substance of interest and should be able to discriminate between compounds of closely related structures which are likely to be present."
* #C134252 "Disintegration" "Test to determine whether tablets capsules disintegrate within the prescribed time when placed in a liquid medium at the experimental conditions."
* #C134253 "Dissolution" "Test to determine compliance with the requirements of the material of interest dissolving into solution."
* #C205012 "Droplet Size" "Tests that determine the size of the liquid drop."
* #C193381 "Foreign and Particulate Matter" "Tests for injections or infusions to check for insoluble particles to confirm that they are not present in excess of specified levels in the solutions."
* #C193381 #C205024  "Metal Detection" "Tests for metallic particles to confirm that they are not present in excess of specified levels."
* #C134255 "Loss on Drying" "Analytical procedures to determine the amount of volatile matter of any kind that is driven off under the conditions specified."
* #C134256 "Microbial Limits" "Tests for the estimation of the number of viable aerobic microorganisms present and for the freedom from designated microbial species in the pharmaceutical articles of all kinds, from raw materials to the finished forms."
* #C205027 "Osmolality/Osmolarity" "Osmolality and osmolarity are measurements of the solute concentration of a solution. Osmolality is expressed in terms of the weight of the solvent and osmolarity is expressed in terms of solvent volume."
* #C134257 "Particle Size Distribution" "Analytical procedures that utilize mechanical sieving for deducing the particle-size distribution of a powdered solid."
* #C134260 "Bulk Density" "Tests that determine the ratio of the mass of an untapped powder sample and its volume including the contribution of the interparticulate void volume."
* #C134263 "Conductivity" "Electrical conductivity is a measure of the ion-facilitated electron flow through it."
* #C133974 "Crystallinity" "The detection and/or quantification of the amount of amorphous material within a highly crystalline substance."
* #C133975 "Friability" "The percent loss of a tablet due to mechanical action that results in fracture or breaking during the test"
* #C134264 "Hardness" "A test used to identify the ability of a material to resist mechanical deformation such as scratching or penetration by other substances."
* #C63394 "Melting Point" "The temperature at the which a substance changes from solid to a liquid state at atmospheric pressure."
* #C103201 "Optical Rotation" "A property of many pharmaceutical substances to rotate an incident plane of polarized light so that the transmitted light emerges at a measurable angle to the plane of the incident light."
* #C205029 "pH" "The measure of acidity or alkalinity of an aqueous solution."
* #C60821 "Solubility" "A chemical property referring to the ability for a given substance, the solute, to dissolve in a solvent. It is measured in terms of the maximum amount of solute dissolved in a solvent at equilibrium."
* #C64832 "Specific Gravity" "The ratio of the density of any substance to the density of some other substance taken as standard, water being the standard for liquids and solids, and hydrogen or air being the standard for gases."
* #C25483 "Material Properties/Measurements" "Dimensions and physical properties of the material of interest including tablets, capsule, soft gel capsule, granulate or pellet, etc."
* #C25483 #C205022 "Individual Weight" "The weight of a single unit of the material of interest. Example: 800 mg tablet"
* #C25483 #C205017 "Group Weight" "The sum of weights of material of interest across a specified collection of units"
* #C25483 #C205209 "Average Weight" """The sum of weights of material of interest across multiple units divided by the number of units included in the sum."""
* #C25483 #C205053 "Weight Variation" """The difference in weights of the material of interest. Examples: 2%, 5 mg, 2.5 % note: may be a percent, a value, or a percent relative standard deviation. [Source: SME Defined]"""
* #C25483 #C205021 "Individual Fill Weight" """The weight of material of interest within a single unit. Example: 1 gram (in each vial), 200 mg (in each capsule) note: could be a capsule, vial, or bottle."""
* #C25483 #C205016 "Group Fill Weight" "The sum of fill weights of material of interest across a specified collection of units"
* #C25483 #C205206 "Average Fill Weight" """The sum of fill weights of material of interest across multiple units divided by the number of units included in the sum."""
* #C25483 #C205045 "Target Group Weight Gain %" """A predetermined percentage weight increases for a set of units resulting from of an action such as coating. Example: 3% (weight gain after coating) note: this can be associated with a bulk material or a single unit."""
* #C25483 #C205036 "Shell Weight" "The weight of outer casing (\"shell\") into which material of interest is filled. Example: 20 mg"
* #C25483 #C205011 "Orifice Location" "The position of hole drilled in the unit dose."
* #C25483 #C205010 "Orifice Diameter" "The length of a straight line measurement across the center of the hole drilled in the unit dose."
* #C25483 #C205009 "Orifice Depth" "The measurement of the penetration of the hole drilled in the unit dose as measured from the outer edge to the deepest point of penetration."
* #C25483 #C205037 "Drilled Side (Single or Double)" "An observation if one or both sides of the unit dose has been drilled."
* #C25483 #C205025 "Number of Orifices" "The total count of holes drilled in the unit dose. [Source: SME Defined]"
* #C25483 #C205034 "Ribbon Thickness" "The dimension between two surfaces of a continuous sheet of compressed material in preparation for subsequent processing."
* #C25483 #C205033 "Ribbon Density" "The compactness of a continuous sheet of compressed material in preparation for subsequent processing."
* #C25483 #C205035 "Seam Thickness" "The measurement of overlap common to two edges of the same material joined together. Example: 1 mm"
* #C25483 #C205005 "Lock Length" "The length of a straight line measurement from the longest edge-to-edge distance through a Capsule body and cap that have been coupled such that the locking rings are sealed as designed."
* #C25483 #C205044 "Tablet/Capsule Length" "The length of a straight line measurement from the longest edge-to-edge distance through the Tablet/Capsule."
* #C25483 #C205043 "Tablet/Capsule Diameter" "The length of a straight line measurement across the circular center of a Tablet/Capsule."
* #C25483 #C205042 "Tablet Thickness" "The length of a straight line measurement from the shortest edge-to-edge distance through a Tablet."
* #C134266 "Tap Density" "An increased bulk density attained after mechanically tapping the container containing the powder sample. (aka - tapped density)"
* #C205049 "Transdermal Properties" """Tests that determine the physical properties of transdermal systems. Example: Peel adhesion test, Tack test, Cold Flow test, etc."""
* #C133979 "Viscosity/Rheological Properties" "Tests to measure a property of liquids that is closely related to the resistance to flow."
* #C134267 "Plume Geometry" "A test that measures the spray pattern characteristics, including shape and size of the evolving spray cloud under defined experimental and instrumental test conditions."
* #C134269 "Polymorphism" """Tests to determine the different crystalline forms of a given drug substance"""
* #C205030 "Porosity" "Tests that measure the empty spaces/voids in the material."
* #C134270 "Potency" "Tests to measure the biological activity using a suitably quantitative biological assay (also called potency assay or bioassay), based on the attribute of the product which is linked to the relevant biological properties."
* #C133983 "Pyrogenicity/Endotoxin" "Tests designed to limit to an acceptable level the risks of febrile reaction in the patient to the administration, by injection, of the product concerned. The test involves measuring the rise in temperature of rabbits following the intravenous injection of a test solution and is designed for products that can be tolerated by the test rabbit in a dose not to exceed 10 mL/kg injected intravenously within a period of NMT 10 min."
* #C134272 "Reconstitution Time" "Measurement of how long it takes to restore something dried to its original state of liquid."
* #C133985 "Redispersibility" "Testing of oral suspensions that settle on storage (produce sediment) to measure the time required to achieve resuspension."
* #C205032 "Refractive Index" "Tests performed to determine the ratio of velocity of light in air to the velocity of light in the substance."
* #C134276 "Residue on Ignition" "Tests to measure the amount of residual substance not volatilized from a sample when the sample is ignited in the presence of sulfuric acid. This test is usually used for determining the content of inorganic impurities in an organic substance."
* #C134277 "Spray Pattern" "Tests to determine the size of the mist formed by spraying. The measurement is made for the longest axis (x axis), and the ratio of longest to shortest axes (x/y ratio)."
* #C134278 "Sterility" "Tests done under aseptic conditions to ensure that there are no contaminating micro-organism present in the sample."
* #C134113 "Syringe Functionality" "Tests performed on syringes to ensure that It operates as specified."
* #C134114 "Total Organic Carbon" "An indirect measure of organic molecules present in pharmaceutical waters measured as carbon."
* #C200004 "Cytotoxicity" "Test methods designed to evaluate the acute adverse biological effects of extractables from medical device materials."
* #C205023 "Mechanical Integrity" "Test that measures what amount of force is needed to alter the mechanical integrity of a construct."
* #C205041 "Surface Area" "Total surface area of a 2D or 3D material."
* #C18951 "Post-translational Modifications" "Test to measure if the protein undergoing post translational modification which include glycosylation etc."
* #C18951 #C16643 "Glycosylation" "Post translation modification due to addition of sugar."
* #C18951 #C205054 "Thrombin Peptide Map" "Map of peptides derived from digestion of protein with thrombin."
* #C18951 #C205031 "Sialylation" "Post translational modification of proteins by sialylation."
* #C18951 #C205002 "Amidation" "Testing for and acid containing residue conversion to an amide."
* #C18951 #C205008 "Deamidation" "Testing for an amide residue conversion to an acid."
* #C205000 "Functional Assays" "Functional assay used to quantify functioning of an active substance rather than just its quantity. Common uses are: showing that a drug target fits the desired functionality and quality profile before moving on to the next stage of development; and comparison of biosimilars with innovator products."
* #C205013 "Elemental Analysis" "The relative proportion of elements present in a sample."
* #C74723 "Turbidity" "Measurement of the clarity and degree of opalescence of liquids by comparison of the solutions in diffused daylight after preparation of the reference suspension."
* #C204971 "Impurity" "Analytical procedures to establish material purity by determining the presence of a material or component of a material that is not defined as the material."
* #C204971 #C205039 "Specified Identified Impurity" "Testing for an impurity that is individually listed and limited with a specific acceptance criterion in the new drug substance or drug product specification and for which a structured characterization has been achieved. Note: this includes degradation products for tests conducted on drug products."
* #C204971 #C205040 "Specified Unidentified Impurity" """Testing for an impurity that is individually listed and limited with a specific acceptance criterion in the new drug substance or drug product specification and that is defined solely by qualitative analytical properties (e.g., chromatographic retention time) due to the lack of achieving a structured characterization. Note: this includes degradation products for tests conducted on drug products."""
* #C204971 #C205052 "Unspecified Impurity" """Testing for an impurity that is limited by a general acceptance criterion, but not individually listed with its own specific acceptance criterion, in the new drug substance or drug product specification. Note: this includes degradation products for tests conducted on drug products."""
* #C204971 #C205047 "Total Impurities" """The sum of all impurities at a level greater than (>) the reporting threshold. Note: this includes degradation products for tests conducted on drug products."""
* #C204971 #C205048 "Total Unknown Impurities" """The sum of unknown (unidentified) impurities in a new drug substance or drug product specification. Note: Total impurities includes all impurities while Total Unknown impurities only includes all the unknown impurities."""
* #C204971 #C205051 "Identified Impurity under IT, Monitored as Unspecified" """Identification (chemical name and/or UNII code) of all the identified (known) impurities that are being controlled as \"unspecified impurities\" rather than \"Specified Identified Impurity\" due to the level being consistently below the ICH identification threshold (IT) value. Note: this includes degradation products for tests conducted on drug products."""
* #C204971 #C205014 "Elemental Impurity" "Analytical procedures that determine the amount of single elements in drug products or drug product components."
* #C204971 #C204890 "Impurity Chemical" "Analytical procedures to establish chemical purity by determining the presence of a component of the material that is not the chemical entity defined as the material."
* #C204971 #C134254 "Impurities/Degradation Products/Related Substances" "Tests that establish the characteristic and uniqueness of the substance of interest and should be able to discriminate between compounds of closely related structures which are likely to be present. Includes leachables and extractables."
* #C204971 #C134002 "Residual Solvent" """Tests performed to determine if organic volatile chemicals that are used or produced in manufacture of drug substance or excipients, or in the preparation of drug products are present in the pharmaceuticals."""
// Manufactured Dose Form Terminology (hierarchical)
* #C45299 "Gas"
* #C45298 "Liquid"
* #C45298  #C154598 "Solution" 
* #C149895 "Semi-solid"
* #C45300 "Solid"
* #C45300 #C154433 "Capsule" 
* #C45300 #C154605 "Tablet" 

//* #batchsize "Batch Quantity"
//* #batchinfo "Batch Formula Additional Information"
//* #BatchUtil "Batch Utilization"
//* #info "Product Part Additional Information"

