ValueSet: EVMPDSubstanceClassification
Id: evmpd-substance-classification
Title: "EVMPD Substance Classification"
Description: "EudraVigilance eXtended Medicinal Product Dictionary (XEVMPD) substance classes"
* $EMAIDMP#1 "Chemical"
* $EMAIDMP#17 "Mixture"
* $EMAIDMP#2 "Nucleic Acid"
* $EMAIDMP#3 "Polymer"
* $EMAIDMP#4 "Protein - Other"
* $EMAIDMP#5 "Protein - Vaccine"
* $EMAIDMP#7 "Structurally Diverse Substance - Immunoglobulin"
* $EMAIDMP#6 "Structurally Diverse Substance - Vaccine"
* $EMAIDMP#10 "Structurally Diverse Substance - Allergen"
* $EMAIDMP#11 "Structurally Diverse Substance -  Cell therapy"
* $EMAIDMP#9 "Structurally Diverse Substance -  Herbal"
* $EMAIDMP#12 "Structurally Diverse Substance - Other"
* $EMAIDMP#8 "Structurally Diverse Substance -  Blood derived"

ValueSet: PqcmcStabilityStudyReasonTerminology
Id: pqcmc-stability-study-reason-terminology
Title: "Stability Study Reason Terminology"
Description: "Terminology used to qualify the information pertaining to stability study reason data in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C115123 "Abbreviated New Animal Drug Application"
* $NCIT#C73113 "Abbreviated New Drug Application"
* $NCIT#C96089 "Annual Report"
* $NCIT#C96094 "Supplement to an Approved Application"
* $NCIT#C71778 "Biologics License Application"
* $NCIT#C70877 "Master File"
* $NCIT#C115122 "Generic Investigational New Animal Drug File"
* $NCIT#C80440 "Humanitarian Device Exemption (HDE)"
* $NCIT#C82667 "Investigational Device Exemption"
* $NCIT#C96091 "Investigational New Animal Drug File"
* $NCIT#C96090 "Investigational New Drug Application"
* $NCIT#C96092 "New Active Ingredient"
* $NCIT#C72901 "New Animal Drug Application"
* $NCIT#C72899 "New Drug Application"
* $NCIT#C70880 "Premarket Approval"
* $NCIT#C80442 "Premarket Notification 510(K)"

ValueSet: PqcmcIntervalDescriptionCodeTerminology
Id: pqcmc-interval-description-code-terminology
Title: "Interval Description Code Terminology"
Description: "Terminology used to qualify the information pertaining to interval description codes in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C96154 "Ambient Delayed Testing"
* $NCIT#C96151 "Delayed Testing"
* $NCIT#C96153 "Frozen Delayed Testing"
* $NCIT#C96150 "Immediate Testing"
* $NCIT#C96155 "Refrigerated Delayed Testing"

ValueSet: PqcmcStudyTypeTerminology
Id: pqcmc-study-type-terminology
Title: "Study Type Terminology"
Description: "Terminology used to qualify the information pertaining to study types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134028 "Complex"
* $NCIT#C134027 "Cycled-Simple"
* $NCIT#C96087 "Photostability"
* $NCIT#C134026 "Standard"

ValueSet: PqcmcExpirationDateClassificationTerminology
Id: pqcmc-expiration-date-classification-terminology
Title: "Expiration Date Classification Terminology"
Description: "Terminology used to qualify the information pertaining to expiration date classification functions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C185182 "Approved"
* $NCIT#C48660 "Not Applicable"
* $NCIT#C185188 "Proposed"

ValueSet: PqcmcRetestDateClassificationTerminology
Id: pqcmc-retest-date-classification-terminology
Title: "Retest Date Classification Terminology"
Description: "Terminology used to qualify the information pertaining to retest date classification functions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C185186 "Adequate"
* $NCIT#C48660 "Not Applicable"
* $NCIT#C185188 "Proposed"

ValueSet: PqActionRelationTypes
Id: pqcmc-action-relaiton-types
Title: "ActionRelationTypes"
Description: "subset of http://hl7.org/fhir/action-relationship-type used for quality specification stage relationshps"
* $ART#concurrent
* $ART#after

CodeSystem: PqcmcNameTypesCodes
Id: pqcmc-cs-name-types
Title: "Code System PQCMC Name Types"
Description: "Name types for the name element in SubstanceDefintion."
//* ^url =  http://hl7.org/fhir/us/pq-cmc/CodeSystem/pqcmc-cs-name-types
* #CAS "CAS Number"
* #INN "INN"
* #USAN "USAN"
* #IUPAC "IUPAC Name"
* #ISBT "ISBT 128"
* #Company "Company Code"
* #Substance "Substance Name"

ValueSet: CmcCompSectionTypesVS
Id: cmc-comp-section-types-vs
Title: "eCTD sections Value Set"
Description: "Value set of all codes in Code system PQCMC Comp Section Types for bindings that require a valueset instead of the code systme."

* include codes from system http://hl7.org/fhir/us/pq-cmc/CodeSystem/pqcmc-comp-section-types

//ValueSet: PqcmcNameTypes
//Id: pqcmc-name-types
//Title: "Name Types"
//Description: "Value set of all the values in PqcmcNameTypesCodes."
//* include codes from system http://hl7.org/fhir/us/pq-cmc/codesystem/pqcmc-name-types

CodeSystem: PqcmcCompSectionTypes
Id: pqcmc-comp-section-types
Title: "Code system PQCMC Comp Section Types"
Description: "Classification of a sections of a PQ/CMC composition/document generally based on eCTD Module 3 section numbering for product and substance. A composition can have many section codes."
//* ^url =  http://hl7.org/fhir/us/pq-cmc/CodeSystem/pqcmc-comp-section-types
* #32S10 "Substance General Information"
* #32S11 "Substance Nomenclature"
* #32S12 "Substance Structure"
* #32S13 "Substance General Properties"
* #32S20 "Substance Manufacture"
* #32S21 "Substance Manufacturers"
* #32S22 "Substance Description of Manufacturing Process and Process Controls"
* #32S23 "Substance Control of Materials"
* #32S24 "Substance Controls of Critical Steps and Intermediates"
* #32S25 "Substance Process Validation and/or Evaluation"
* #32S26 "Substance Manufacturing Process Development"
* #32S30 "Substance Characterization"
* #32S31 "Substance Elucidation of Structure and other Characteristics"
* #32S32 "Substance Impurities"
* #32S40 "Substance Control of Drug Substance"
* #32S41 "Substance Specification"
* #32S42 "Substance Analytical Procedures"
* #32S43 "Substance Validation of Analytical Procedures"
* #32S44 "Substance Batch Analyses"
* #32S45 "Substance Justification of Specification"
* #32S50 "Substance Reference Standards or Materials"
* #32S60 "Substance Container Closure System"
* #32S70 "Substance Stability"
* #32S71 "Substance Stability Summary and Conclusions"
* #32S72 "Substance Postapproval Stability Protocol and Stability Commitment"
* #32S73 "Substance Stability Data"
* #32P10 "Product Description and Composition of the Drug Product"
* #32P11 "Product Description"
* #32P12 "Product Composition"
* #32P20 "Product Pharmaceutical Development"
* #32P21 "Product Components of the Drug Product"
* #32P22 "Product Drug Product"
* #32P23 "Product Manufacturing Process Development"
* #32P24 "Product Container Closure System"
* #32P25 "Product Microbiological Attributes"
* #32P26 "Product Compatibility"
* #32P30 "Product Manufacture"
* #32P31 "Product Manufacturers"
* #32P32 "Product Batch Formula"
* #32P33 "Product Description of Manufacturing Process and Process Controls"
* #32P34 "Product Controls of Critical Steps and Intermediates"
* #32P35 "Product Process Validation and/or Evaluation"
* #32P40 "Product Control of Excipients"
* #32P41 "Excipients Specification"
* #32P42 "Product Analytical Procedures"
* #32P43 "Product Validation of Analytical Procedures"
* #32P44 "Product Justification of Specifications"
* #32P45 "Product Excipients of Human or Animal Origin"
* #32P46 "Product Novel Excipients"
* #32P50 "Product name  dosage form"
* #32P51 "Product Specification"
* #32P52 "Product Analytical Procedures"
* #32P53 "Product Validation of Analytical Procedures"
* #32P54 "Product Batch Analyses"
* #32P55 "Product Characterization of Impurities"
* #32P56 "Product Justification of Specifications"
* #32P60 "Product Reference Standards or Materials"
* #32P70 "Product Container Closure System"
* #32P80 "Product Stability"
* #32P81 "Product Stability Summary and Conclusion"
* #32P82 "Product Postapproval Stability Protocol and Stability Commitment"
* #32P83 "Product Stability Data"
* #SP4151 "Quality Specification"
* #SP4454 "Batch Analyses"
* #SP7383 "Stability Data"

ValueSet: PqcmcBatchUtilizationTerminology
Id: pqcmc-batch-utilization-terminology
Title: "Batch utilization Terminology"
Description: "Terminology used to qualify the information pertaining to batch utilization in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C133994 "Bioequivalence"
* $NCIT#C133992 "Clinical"
* $NCIT#C133990 "Commercial"
* $NCIT#C133991 "Development"
* $NCIT#C133993 "Validation"
* $NCIT#C185328 "Stability Study"

//ValueSet: PqcmcChemicalStructureDataFileOriginTerminology
//Id: pqcmc-chemical-structure-datafile-origin-terminology
//Title: "Chemical Structure Datafile Origin Terminology"
//Description: "Terminology used to qualify the information pertaining to chemical structure data file origins in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
//* $NCIT#C16275 "Calculated"
//* $NCIT#C133995 "Experimental"

ValueSet: PqcmcChemicalStructureDataFileTypeTerminology
Id: pqcmc-chemical-structure-datafile-type-terminology
Title: "Chemical Structure Data File Type Terminology"
Description: "Terminology used to qualify the information pertaining to chemical structure data file types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C54683 "InChI File (small molecule)"
* $NCIT#C133997 "mmCIF (large molecules)"
* $NCIT#C133910 "MOLFILE"
* $NCIT#C49039 "PDB"
* $NCIT#C133996 "SDF"
* $NCIT#C54684 "SMILES"
* $NCIT#C85435 "SVG"

ValueSet: PqcmcClosureTypeTerminology
Id: pqcmc-closure-type-terminology
Title: "Closure Type Terminology"
Description: "Terminology used to qualify the information pertaining to closure types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C96113 "Childresistant, Metal"
* $NCIT#C96114 "Childresistant, Plastic"
* $NCIT#C96115 "Continuous Thread, Metal"
* $NCIT#C96116 "Continuous Thread, Plastic"
* $NCIT#C96125 "Crown, Metal"
* $NCIT#C96128 "FlipTop (Dispensing), Plastic"
* $NCIT#C96129 "Hinged (Dispensing), Plastic"
* $NCIT#C96130 "Linerless, Plastic"
* $NCIT#C96126 "Lug, Metal"
* $NCIT#C96124 "Presson, Composite"
* $NCIT#C96123 "Presson/twistoff, Metal"
* $NCIT#C96131 "Pump (Dispensing), Plastic"
* $NCIT#C96132 "Pushpull (Dispensing), Plastic"
* $NCIT#C96127 "Rollon, Metal"
* $NCIT#C96133 "Snapon Cap, Plastic"
* $NCIT#C96134 "Sniptip (Dispensing), Plastic"
* $NCIT#C96139 "Stopper"
* $NCIT#C96120 "Tamperevident, Composite"
* $NCIT#C96117 "Tamperevident, Metal"
* $NCIT#C96118 "Tamperevident, Plastic"
* $NCIT#C96140 "Tie"
* $NCIT#C96135 "Toggleswing (Dispensing), Plastic"
* $NCIT#C96136 "Trigger Sprayer (Dispensing), Plastic"
* $NCIT#C96137 "Twist Open/Close (Dispensing), Plastic"
* $NCIT#C96122 "Vacuum, Composite"
* $NCIT#C96119 "Vacuum, Metal"
* $NCIT#C96121 "Vacuum, Plastic"
* $NCIT#C96138 "Valved (Dispensing), Plastic"

ValueSet: PqcmcConformanceCriteriaTerminology
Id: pqcmc-conformance-to-criteria-terminology
Title: "Conformance to Criteria Terminology"
Description: "Terminology used to qualify the information pertaining to conformance to criteria in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C80262 "Conforms"
* $NCIT#C133998 "Does not conform"

ValueSet: PqcmcContainerOrientationTerminology
Id: pqcmc-container-orientation-terminology
Title: "Container Orientation Terminology"
Description: "Terminology used to qualify the information pertaining to container orientation in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C25241 "Horizontal"
* $NCIT#C133999 "Inverted"
* $NCIT#C86043 "Upright"
* $NCIT#C133915 "Valvedown"
* $NCIT#C133914 "Valveup"

ValueSet: PqcmcContainerTypeTerminology
Id: pqcmc-container-type-terminology
Title: "Container Type Terminology"
Description: "Terminology used to qualify the information pertaining to container types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C43165 "AMPULE"
* $NCIT#C43166 "APPLICATOR"
* $NCIT#C43167 "BAG"
* $NCIT#C43168 "BLISTER PACK"
* $NCIT#C43169 "BOTTLE"
* $NCIT#C43170 "BOTTLE, DISPENSING"
* $NCIT#C43171 "BOTTLE, DROPPER"
* $NCIT#C43172 "BOTTLE, GLASS"
* $NCIT#C43173 "BOTTLE, PLASTIC"
* $NCIT#C43174 "BOTTLE, PUMP"
* $NCIT#C43175 "BOTTLE, SPRAY"
* $NCIT#C43176 "BOTTLE, UNITDOSE"
* $NCIT#C43177 "BOTTLE, WITH APPLICATOR"
* $NCIT#C43178 "BOX"
* $NCIT#C43179 "BOX, UNITDOSE"
* $NCIT#C43180 "CAN"
* $NCIT#C43181 "CANISTER"
* $NCIT#C96143 "Canisters, lined"
* $NCIT#C92708 "CAPSULE"
* $NCIT#C43182 "CARTON"
* $NCIT#C43183 "CARTRIDGE"
* $NCIT#C43184 "CASE"
* $NCIT#C43185 "CELLO PACK"
* $NCIT#C43186 "CONTAINER"
* $NCIT#C43187 "CUP"
* $NCIT#C43188 "CUP, UNITDOSE"
* $NCIT#C43189 "CYLINDER"
* $NCIT#C43190 "DEWAR"
* $NCIT#C43191 "DIALPACK"
* $NCIT#C96141 "Dish, Petri"
* $NCIT#C43192 "DOSE PACK"
* $NCIT#C43193 "DRUM"
* $NCIT#C96144 "Flask"
* $NCIT#C79135 "FLEXIBLE INTERMEDIATE BULK CONTAINER"
* $NCIT#C16738 "INHALER"
* $NCIT#C43194 "INHALER, REFILL"
* $NCIT#C43195 "JAR"
* $NCIT#C43196 "JUG"
* $NCIT#C43197 "KIT"
* $NCIT#C48626 "NOT STATED"
* $NCIT#C43233 "PACKAGE"
* $NCIT#C43198 "PACKAGE, COMBINATION"
* $NCIT#C43199 "PACKET"
* $NCIT#C79136 "PAIL"
* $NCIT#C82332 "PATCH"
* $NCIT#C96142 "Plate, Microwell"
* $NCIT#C43200 "POUCH"
* $NCIT#C43201 "SUPERSACK"
* $NCIT#C43202 "SYRINGE"
* $NCIT#C43203 "SYRINGE, GLASS"
* $NCIT#C43204 "SYRINGE, PLASTIC"
* $NCIT#C43205 "TABMINDER"
* $NCIT#C43206 "TANK"
* $NCIT#C53438 "TRAY"
* $NCIT#C42794 "TUBE"
* $NCIT#C43207 "TUBE, WITH APPLICATOR"
* $NCIT#C43226 "VIAL"
* $NCIT#C43208 "VIAL, DISPENSING"
* $NCIT#C43209 "VIAL, GLASS"
* $NCIT#C43210 "VIAL, MULTIDOSE"
* $NCIT#C43211 "VIAL, PATENT DELIVERY SYSTEM"
* $NCIT#C43212 "VIAL, PHARMACY BULK PACKAGE"
* $NCIT#C43213 "VIAL, PIGGYBACK"
* $NCIT#C43214 "VIAL, PLASTIC"
* $NCIT#C43215 "VIAL, SINGLEDOSE"
* $NCIT#C43216 "VIAL, SINGLEUSE"

//alueSet: PqcmcCoPackagedIndicatorTerminology
//Id: pqcmc-copackaged-indicator-terminology
//Title: "Co-packaged Indicator Terminology"
//Description: "Terminology used to qualify the information pertaining to copackaged indicators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
//* $NCIT#C49487 "No"
//* $NCIT#C49488 "Yes"

ValueSet: PqcmcDrugProductComponentFunctionCategoryTerminology
Id: pqcmc-drug-product-component-function-category-terminology
Title: "Drug Product Component Function Category Terminology"
Description: "Terminology used to qualify the information pertaining to drug product component function categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C82533 "Active Ingredient"
* $NCIT#C2140 "Adjuvant"
* $NCIT#C42637 "Inactive Ingredient"

//ValueSet: PqcmcDrugSubstanceProductIndicatorTerminology
//Id: pqcmc-drug-substance-product-indicator-terminology
//Title: "Drug substance Product Indicator Terminology"
//Description: "Terminology used to qualify the information pertaining to drug substance product indicators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
//* $NCIT#C1909 "Product"
//* $NCIT#C45306 "SUBSTANCE"

ValueSet: PqcmcExcipientFunctionTerminology
Id: pqcmc-excipient-function-terminology
Title: "Excipient Function Terminology"
Description: "Terminology used to qualify the information pertaining to excipient functions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C176637 "Absorption modifier"
* $NCIT#C89528 "Adhesive"
* $NCIT#C176642 "Adsorbent"
* $NCIT#C176643 "Air displacement"
* $NCIT#C42654 "Anticaking agent"
* $NCIT#C275 "Antioxidant"
* $NCIT#C42647 "Binder"
* $NCIT#C70815 "Buffering agent"
* $NCIT#C176644 "Bulking agent"
* $NCIT#C92708 "CAPSULE"
* $NCIT#C176645 "Carrier"
* $NCIT#C360 "Chelating agent"
* $NCIT#C42656 "Coloring agent"
* $NCIT#C176646 "Complexing agent"
* $NCIT#C53306 "Cryoprotectant"
* $NCIT#C176647 "Denaturant"
* $NCIT#C42648 "Disintegrant"
* $NCIT#C42662 "Dispersing agent"
* $NCIT#C176638 "Effervescent agent"
* $NCIT#C176632 "Emollient"
* $NCIT#C73477 "Emulsifying Excipient"
* $NCIT#C176633 "Emulsion stabilizing agent"
* $NCIT#C42650 "Filler"
* $NCIT#C176648 "Film coating agent"
* $NCIT#C176634 "Foam stabilizing agent"
* $NCIT#C176649 "Free radical scavenger"
* $NCIT#C176650 "Gelling agent"
* $NCIT#C176651 "Humectant"
* $NCIT#C42657 "Ink"
* $NCIT#C42653 "Lubricant"
* $NCIT#C176652 "Lyophilization aid"
* $NCIT#C176653 "Matrixforming agent"
* $NCIT#C176654 "Microencapsulating agent"
* $NCIT#C176655 "Ointment base"
* $NCIT#C176656 "Opacifier"
* $NCIT#C176635 "Organoleptic agent"
* $NCIT#C176657 "Osmotic agent"
* $NCIT#C176658 "pH modifier"
* $NCIT#C55826 "Plasticizer"
* $NCIT#C176659 "Polishing agent"
* $NCIT#C176660 "Polymers for ophthalmic use"
* $NCIT#C42659 "Preservative"
* $NCIT#C176661 "Propellant"
* $NCIT#C176639 "Reducing agent"
* $NCIT#C176662 "Release modifying agent"
* $NCIT#C176640 "Solubilizing agent"
* $NCIT#C45790 "Solvent"
* $NCIT#C176636 "Stabilizer"
* $NCIT#C176663 "Suppository base"
* $NCIT#C42739 "Surfactant"
* $NCIT#C42660 "Suspending agent"
* $NCIT#C176641 "Tonicity agent"
* $NCIT#C176664 "Transdermal delivery component"
* $NCIT#C176665 "Transfer ligand"
* $NCIT#C927 "Vehicle"
* $NCIT#C176666 "Viscosity modifier"
* $NCIT#C176667 "Waterrepelling agent"
* $NCIT#C176668 "Wetting agent"

ValueSet: PqcmcImpurityClassificationTerminology
Id: pqcmc-impurity-classification-terminology
Title: "Impurity Classification Terminology"
Description: "Terminology used to qualify the information pertaining to impurity classifications in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C176816 "Degradant"
* $NCIT#C185190 "Elemental Impurity"
* $NCIT#C134001 "Inorganic Impurity"
* $NCIT#C185192 "Leachable Material"
* $NCIT#C92081 "Microbial Contamination"
* $NCIT#C176812 "Process Related Impurity"
* $NCIT#C176813 "Product Related Impurity"
* $NCIT#C176815 "Residual Solvent"

ValueSet: PqcmcInterpretationCodeTerminology
Id: pqcmc-interpretation-code-terminology
Title: "Interpretation Code Terminology"
Description: "Terminology used to qualify the information pertaining to numeric interpretation codes in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C48793 "EQ"
* $NCIT#C61585 "LT (less than)"
* $NCIT#C61584 "MT (more than)"
* $NCIT#C61583 "NLT (not less than)"
* $NCIT#C61586 "NMT (not more than)"
* $NCIT#C48660 "Not Applicable"

ValueSet: PqcmcProcessRelatedImpurityCategoryTerminology
Id: pqcmc-impurity-classification-category-terminology
Title: "Impurity classification Category Terminology"
Description: "Terminology used to qualify the information pertaining to process related impurity categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134001 "Inorganic"
* $NCIT#C134000 "Organic"
* $NCIT#C176815 "Residual Solvent"

//
//ValueSet: PqcmcProductRelatedImpurityCategoryTerminology
//Id: pqcmc-product-related-impurity-category-terminology
//Title: "Product Related Impurity Category Terminology"
//Description: "Terminology used to qualify the information pertaining to product related impurity categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
//* $NCIT#C176816 "Degradants"
//* $NCIT#C176813 "Product Related"

ValueSet: PqcmcQualityBenchmarkTerminology
Id: pqcmc-quality-benchmark-terminology
Title: "Quality Standard Terminology"
Description: "Terminology used to qualify the information pertaining to quality benchmarks in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C176793 "BP"
* $NCIT#C134009 "Company Standard"
* $NCIT#C134007 "EP"
* $NCIT#C134008 "JP"
* $NCIT#C134006 "USPNF"

ValueSet: PqcmcSourceTypeTerminology
Id: pqcmc-source-type-terminology
Title: "Source Type Terminology"
Description: "Terminology used to qualify the information pertaining to source types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C14182 "Animal"
* $NCIT#C18634 "Animalderived indirectly"
* $NCIT#C48807 "Chemical"
* $NCIT#C14225 "Human"
* $NCIT#C14227 "Insect"
* $NCIT#C14329 "Microbial"
* $NCIT#C14258 "Plant"

ValueSet: PqcmcSpecificationStatusTerminology
Id: pqcmc-specification-status-terminology
Title: "Specification Status Terminology"
Description: "Terminology used to qualify the information pertaining to specification statuses in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C25425 "Approved"
* $NCIT#C48660 "Not Applicable"
* $NCIT#C134011 "Not Approved"
* $NCIT#C134012 "Reported in a CBE or AR"
* $NCIT#C134010 "Tentatively Approved"

ValueSet: PqcmcSpecificationTypeTerminology
Id: pqcmc-specification-type-terminology
Title: "Specification Type Terminology"
Description: "Terminology used to qualify the information pertaining to specification types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134021 "Drug Product"
* $NCIT#C134022 "Drug Substance"
* $NCIT#C133931 "Raw Materials/Excipients/Intermediates/Reagents"

ValueSet: PqcmcSponsorIdentifierTypeTerminology
Id: pqcmc-sponsor-identifier-type-terminology
Title: "Sponsor Identifier Type Terminology"
Description: "Terminology used to qualify the information pertaining to sponsor identifier types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134005 "CFN"
* $NCIT#C134003 "DUNS"
* $NCIT#C134004 "FEI"
* $NCIT#C17998 "Unknown"

ValueSet: PqcmcStorageConditionsTerminology
Id: pqcmc-storage-conditions-terminology
Title: "Storage Conditions Terminology"
Description: "Terminology used to qualify the information pertaining to storage conditions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C133936 "20 +/ 5 degrees C"
* $NCIT#C134018 "25 +/ 2 degrees C/40% +/ 5%RH"
* $NCIT#C134014 "25 +/ 2 degrees C/60% +/ 5%RH"
* $NCIT#C134015 "30 +/ 2 degrees C/65% +/ 5%RH"
* $NCIT#C134017 "30 +/ 2 degrees C/75% +/ 5%RH"
* $NCIT#C134019 "30 degrees C +/ 2 degrees C/35%RH +/ 5%RH"
* $NCIT#C134016 "40 +/ 2 degrees C/75% +/ 5%RH"
* $NCIT#C133940 "40 degrees C +/ 2 degrees C/not more than (NMT) 25%RH"
* $NCIT#C133935 "5 +/ 3 degrees C"
* $NCIT#C96148 "Proprietary"

ValueSet: PqcmcStrengthOperatorTerminology
Id: pqcmc-strength-operator-terminology
Title: "Strength Operator Terminology"
Description: "Terminology used to qualify the information pertaining to strength operators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C48793 "EQ"
* $NCIT#C61585 "LT (less than)"
* $NCIT#C61584 "MT (more than)"
* $NCIT#C61583 "NLT (not less than)"
* $NCIT#C61586 "NMT (not more than)"
* $NCIT#C48660 "Not Applicable"

ValueSet: PqcmcStrengthTypeTerminology
Id: pqcmc-strength-type-terminology
Title: "Strength Type Terminology"
Description: "Terminology used to qualify the information pertaining to strength types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C45420 "Activity"
* $NCIT#C168628 "Mass"

ValueSet: PqcmcTestCategoryTerminology
Id: pqcmc-test-category-terminology
Title: "Test Category Terminology"
Description: "Terminology used to qualify the information pertaining to test categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C60819 "Assay"
* $NCIT#C158425 "Biological Properties"
* $NCIT#C138990 "Description"
* $NCIT#C138993 "Identification"
* $NCIT#C158423 "Impurities"
* $NCIT#C176810 "Microbiological Properties"
* $NCIT#C176811 "PhysicoChemical Properties"

ValueSet: PqcmcTestMethodOriginTerminology
Id: pqcmc-test-method-origin-terminology
Title: "Test Method Origin Terminology"
Description: "Terminology used to qualify the information pertaining to test method origins in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C96164 "CFR"
* $NCIT#C96102 "Compendial"
* $NCIT#C96103 "Proprietary"

ValueSet: PqcmcTestUsageTerminology
Id: pqcmc-test-usage-terminology
Title: "Test Usage Terminology"
Description: "Terminology used to qualify the information pertaining to test usage in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134029 "Release"
* $NCIT#C134030 "Stability"

ValueSet: PqcmcTestingSiteUniqueIdentifierTypeTerminology
Id: pqcmc-testing-site-unique-identifier-type-terminology
Title: "Testing Site Unique Identifier Type Terminology"
Description: "Terminology used to qualify the information pertaining to testing site unique identifier types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $NCIT#C134005 "CFN"
* $NCIT#C134003 "DUNS"
* $NCIT#C134004 "FEI"
* $NCIT#C17998 "Unknown"

ValueSet: SplPharmaceuticalDosageFormTerminology
Id: spl-pharmaceutical-dosage-form-terminology
Title: "Pharmaceutical Dosage Form Terminology"
Description: "Terminology used for representation of the information on pharmaceutical product dosage form in the framework of the SPL documents."
* $NCIT#C100103 "CELLULAR SHEET"
* $NCIT#C113106 "INJECTABLE FOAM"
* $NCIT#C124794 "TABLET, CHEWABLE, EXTENDED RELEASE"
* $NCIT#C134876 "Chewable Gel"
* $NCIT#C147579 "Tablet with Sensor"
* $NCIT#C17423 "DRUG DELIVERY SYSTEM"
* $NCIT#C25158 "CAPSULE"
* $NCIT#C25394 "PILL"
* $NCIT#C28944 "CREAM"
* $NCIT#C29167 "LOTION"
* $NCIT#C29269 "MOUTHWASH"
* $NCIT#C42679 "DOUCHE"
* $NCIT#C42763 "DRESSING"
* $NCIT#C42887 "AEROSOL"
* $NCIT#C42888 "AEROSOL, FOAM"
* $NCIT#C42889 "AEROSOL, SPRAY"
* $NCIT#C42890 "BEAD"
* $NCIT#C42892 "BAR, CHEWABLE"
* $NCIT#C42893 "TABLET, CHEWABLE"
* $NCIT#C42894 "GUM, CHEWING"
* $NCIT#C42895 "CAPSULE, COATED"
* $NCIT#C42896 "CAPSULE, COATED PELLETS"
* $NCIT#C42897 "TABLET, COATED"
* $NCIT#C42898 "SOLUTION, CONCENTRATE"
* $NCIT#C42899 "INJECTION, SOLUTION, CONCENTRATE"
* $NCIT#C42901 "CRYSTAL"
* $NCIT#C42902 "CAPSULE, DELAYED RELEASE"
* $NCIT#C42903 "GRANULE, DELAYED RELEASE"
* $NCIT#C42904 "CAPSULE, DELAYED RELEASE PELLETS"
* $NCIT#C42905 "TABLET, DELAYED RELEASE"
* $NCIT#C42906 "GEL, DENTIFRICE"
* $NCIT#C42907 "PASTE, DENTIFRICE"
* $NCIT#C42908 "POWDER, DENTIFRICE"
* $NCIT#C42909 "GRANULE, EFFERVESCENT"
* $NCIT#C42910 "TABLET, EFFERVESCENT"
* $NCIT#C42911 "PATCH, EXTENDED RELEASE, ELECTRICALLY CONTROLLED"
* $NCIT#C42912 "ELIXIR"
* $NCIT#C42913 "EMULSION"
* $NCIT#C42914 "INJECTION, EMULSION"
* $NCIT#C42915 "ENEMA"
* $NCIT#C42916 "CAPSULE, EXTENDED RELEASE"
* $NCIT#C42917 "CAPSULE, COATED, EXTENDED RELEASE"
* $NCIT#C42918 "PELLETS, COATED, EXTENDED RELEASE"
* $NCIT#C42920 "FILM, EXTENDED RELEASE"
* $NCIT#C42921 "GRANULE, FOR SUSPENSION, EXTENDED RELEASE"
* $NCIT#C42922 "INSERT, EXTENDED RELEASE"
* $NCIT#C42923 "PATCH, EXTENDED RELEASE"
* $NCIT#C42924 "SUPPOSITORY, EXTENDED RELEASE"
* $NCIT#C42925 "SUSPENSION, EXTENDED RELEASE"
* $NCIT#C42926 "INJECTION, SUSPENSION, EXTENDED RELEASE"
* $NCIT#C42927 "TABLET, EXTENDED RELEASE"
* $NCIT#C42928 "CAPSULE, FILM COATED, EXTENDED RELEASE"
* $NCIT#C42929 "EXTRACT"
* $NCIT#C42930 "TABLET, FILM COATED, EXTENDED RELEASE"
* $NCIT#C42931 "TABLET, FILM COATED"
* $NCIT#C42932 "FILM"
* $NCIT#C42933 "GAS"
* $NCIT#C42934 "GEL"
* $NCIT#C42935 "SOLUTION, GEL FORMING, EXTENDED RELEASE"
* $NCIT#C42936 "CAPSULE, GELATIN COATED"
* $NCIT#C42937 "GLOBULE"
* $NCIT#C42938 "GRANULE"
* $NCIT#C42939 "GRANULE, FOR SOLUTION"
* $NCIT#C42940 "GRANULE, FOR SUSPENSION"
* $NCIT#C42942 "IMPLANT"
* $NCIT#C42943 "PELLET, IMPLANTABLE"
* $NCIT#C42944 "INHALANT"
* $NCIT#C42945 "INJECTION, SOLUTION"
* $NCIT#C42946 "INJECTION"
* $NCIT#C42947 "IRRIGANT"
* $NCIT#C42948 "JELLY"
* $NCIT#C42949 "LINIMENT"
* $NCIT#C42950 "INJECTION, LIPID COMPLEX"
* $NCIT#C42951 "INJECTION, SUSPENSION, LIPOSOMAL"
* $NCIT#C42952 "LIPSTICK"
* $NCIT#C42953 "LIQUID"
* $NCIT#C42954 "CAPSULE, LIQUID FILLED"
* $NCIT#C42955 "LOZENGE"
* $NCIT#C42956 "INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION, EXTENDED RELEASE"
* $NCIT#C42957 "INJECTION, POWDER, LYOPHILIZED, FOR SOLUTION"
* $NCIT#C42958 "INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION"
* $NCIT#C42959 "INJECTION, POWDER, LYOPHILIZED, FOR LIPOSOMAL SUSPENSION"
* $NCIT#C42960 "AEROSOL, METERED"
* $NCIT#C42961 "POWDER, METERED"
* $NCIT#C42962 "SPRAY, METERED"
* $NCIT#C42963 "TABLET, MULTILAYER, EXTENDED RELEASE"
* $NCIT#C42964 "TABLET, MULTILAYER"
* $NCIT#C42965 "OIL"
* $NCIT#C42966 "OINTMENT"
* $NCIT#C42967 "PASTE"
* $NCIT#C42968 "PATCH"
* $NCIT#C42969 "PELLET"
* $NCIT#C42970 "PLASTER"
* $NCIT#C42971 "AEROSOL, POWDER"
* $NCIT#C42972 "POWDER"
* $NCIT#C42973 "POWDER, FOR SOLUTION"
* $NCIT#C42974 "INJECTION, POWDER, FOR SOLUTION"
* $NCIT#C42975 "POWDER, FOR SUSPENSION"
* $NCIT#C42976 "INJECTION, POWDER, FOR SUSPENSION"
* $NCIT#C42977 "INJECTION, POWDER, FOR SUSPENSION, EXTENDED RELEASE"
* $NCIT#C42979 "RINSE"
* $NCIT#C42980 "SALVE"
* $NCIT#C42981 "SHAMPOO"
* $NCIT#C42982 "SHAMPOO, SUSPENSION"
* $NCIT#C42983 "SOAP"
* $NCIT#C42984 "FILM, SOLUBLE"
* $NCIT#C42985 "TABLET, SOLUBLE"
* $NCIT#C42986 "SOLUTION"
* $NCIT#C42987 "SOLUTION, FOR SLUSH"
* $NCIT#C42988 "INJECTION, SUSPENSION, SONICATED"
* $NCIT#C42989 "SPRAY"
* $NCIT#C42990 "SPRAY, SUSPENSION"
* $NCIT#C42991 "STICK"
* $NCIT#C42992 "TABLET, SUGAR COATED"
* $NCIT#C42993 "SUPPOSITORY"
* $NCIT#C42994 "SUSPENSION"
* $NCIT#C42995 "INJECTION, SUSPENSION"
* $NCIT#C42996 "SYRUP"
* $NCIT#C42997 "TABLET, DELAYED RELEASE PARTICLES"
* $NCIT#C42998 "TABLET"
* $NCIT#C42999 "TABLET, ORALLY DISINTEGRATING"
* $NCIT#C43000 "TINCTURE"
* $NCIT#C43001 "TROCHE"
* $NCIT#C43003 "WAFER"
* $NCIT#C43525 "DISC"
* $NCIT#C47892 "TAMPON"
* $NCIT#C47897 "TAPE"
* $NCIT#C47898 "SWAB"
* $NCIT#C47912 "SPONGE"
* $NCIT#C47913 "POULTICE"
* $NCIT#C47914 "STRIP"
* $NCIT#C47915 "INTRAUTERINE DEVICE"
* $NCIT#C47916 "KIT"
* $NCIT#C48624 "NOT APPLICABLE"
* $NCIT#C60884 "CLOTH"
* $NCIT#C60891 "CONCENTRATE"
* $NCIT#C60897 "CREAM, AUGMENTED"
* $NCIT#C60926 "FIBER, EXTENDED RELEASE"
* $NCIT#C60927 "FOR SOLUTION"
* $NCIT#C60928 "FOR SUSPENSION"
* $NCIT#C60929 "FOR SUSPENSION, EXTENDED RELEASE"
* $NCIT#C60930 "GEL, METERED"
* $NCIT#C60931 "INJECTABLE, LIPOSOMAL"
* $NCIT#C60933 "INSERT"
* $NCIT#C60934 "LIQUID, EXTENDED RELEASE"
* $NCIT#C60957 "LOTION, AUGMENTED"
* $NCIT#C60958 "LOTION/SHAMPOO"
* $NCIT#C60984 "OINTMENT, AUGMENTED"
* $NCIT#C60985 "PASTILLE"
* $NCIT#C60988 "RING"
* $NCIT#C60992 "SOLUTION/DROPS"
* $NCIT#C60994 "SOLUTION, GEL FORMING/DROPS"
* $NCIT#C60995 "SUSPENSION/DROPS"
* $NCIT#C60997 "TABLET, COATED PARTICLES"
* $NCIT#C61004 "TABLET, FOR SOLUTION"
* $NCIT#C61005 "TABLET, FOR SUSPENSION"
* $NCIT#C61006 "TABLET, ORALLY DISINTEGRATING, DELAYED RELEASE"
* $NCIT#C64884 "POWDER, EFFERVESCENT"
* $NCIT#C64984 "INTRACAMERAL"
* $NCIT#C69067 "GRANULE, EXTENDED RELEASE"
* $NCIT#C87536 "SMOKE STICK"
* $NCIT#C87537 "SMOKE PAPER"
* $NCIT#C87538 "INTRARUMINAL DEVICE, EXTENDED RELEASE"
* $NCIT#C87539 "TAG"
* $NCIT#C87540 "GRANULE FOR SUSPENSION, DELAYED RELEASE"
* $NCIT#C87541 "POWDER, LYOPHILIZED"
* $NCIT#C87542 "PENDANT"

ValueSet: PqcmcUnitsMeasureTerminology
Id: pqcmc-units-of-measure-terminology
Title: "Units Of Measure Terminology"
Description: "Terminology used to qualify the information pertaining to units of measure in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents.
Note: Inlcudes SPL Unit of Presentation Terminology"
* $UCUM#% "percent"
* $UCUM#%{VolumeToVolume} "percent volume per volume"
* $UCUM#%{WeightToVolume} "percent weight per volume"
* $UCUM#%{WeightToWeight} "percent weight/weight"
* $UCUM#(m2.d) "meter squared in 24 hours"
* $UCUM#[Amb'a'1'U] "Amb a 1 units"
* $UCUM#[arb'U] "ARBITRARY UNITS"
* $UCUM#[AU] "ALLERGY UNITS"
* $UCUM#[BAU] "BIOEQUIVALENT ALLERGY UNITS"
* $UCUM#[Btu] "British Thermal Unit"
* $UCUM#[CCID_50] "CELL CULTURE INFECTIOUS DOSE 50%"
* $UCUM#[CFU] "colony forming units"
* $UCUM#[degF] "degree Fahrenheit"
* $UCUM#[EU] "Ehrlich unit"
* $UCUM#[FFU] "FOCUS-FORMING UNITS"
* $UCUM#[hp_C] "HOMEOPATHIC POTENCY OF CENTESIMAL SERIES"
* $UCUM#[hp_M] "HOMEOPATHIC POTENCY OF MILLESIMAL SERIES"
* $UCUM#[hp_Q] "HOMEOPATHIC POTENCY OF QUINTAMILLESIMAL SERIES"
* $UCUM#[hp_X] "HOMEOPATHIC POTENCY OF DECIMAL SERIES"
* $UCUM#[in-i] "inch"
* $UCUM#[IU] "international unit"
* $UCUM#[lb-av] "pound"
* $UCUM#[lbf-av] "pound foot"
* $UCUM#[Lf] "LIMIT OF FLOCCULATION"
* $UCUM#[oz-av] "ounce"
* $UCUM#[PFU] "PLAQUE-FORMING UNITS"
* $UCUM#[pH] "pH"
* $UCUM#[PNU] "PROTEIN NITROGEN UNITS"
* $UCUM#[ppb] "parts per billion"
* $UCUM#[ppm] "parts per million"
* $UCUM#[ppth] "parts per thousand"
* $UCUM#[pptr] "parts per trillion"
* $UCUM#[psi] "pounds per square inch"
* $UCUM#[pt-us] "pints (US Dry)"
* $UCUM#[qt-us] "quarts (US Dry)"
* $UCUM#[TCID_50] "TISSUE CULTURE INFECTIOUS DOSE 50%"
* $UCUM#[USP'U] "UNITED STATES PHARMACOPEIA UNIT"
* $UCUM#{actuation} "actuation"
* $UCUM#{can} "can"
* $UCUM#{kp_C} "HOMEOPATHIC POTENCY OF CENTESIMAL KORSAKOVIAN SERIES"
* $UCUM#{tbl} "tablet"
* $UCUM#{tot} "particles"
* $UCUM#{vial} "vial"
* $UCUM#{VP} "Viral Particles"
* $UCUM#1 "1*"
* $UCUM#a "year"
* $UCUM#Cel "degree Celsius"
* $UCUM#cm "centimeter"
* $UCUM#cm3 "mL"
* $UCUM#d "day"
* $UCUM#deg "degrees to rotation"
* $UCUM#g "gram"
* $UCUM#gal "gallon"
* $UCUM#h "hour"
* $UCUM#K "degree Kelvin"
* $UCUM#kg "kilogram"
* $UCUM#kgf "kilopond"
* $UCUM#ku "kiloDalton"
* $UCUM#L "liter"
* $UCUM#m "meter"
* $UCUM#m2 "square meter"
* $UCUM#m3 "cubic meter"
* $UCUM#mg "milligram"
* $UCUM#mg% "milligram per 100 milliliters of solution"
* $UCUM#min "minute"
* $UCUM#mm "millimeter"
* $UCUM#mmol "millimole"
* $UCUM#mo "month"
* $UCUM#mol "mole"
* $UCUM#mosm "milliosmole"
* $UCUM#ms "millisiemens"
* $UCUM#N "Newton"
* $UCUM#ng "nanogram"
* $UCUM#nm "nanometer"
* $UCUM#nmol "nanomole"
* $UCUM#pg "picogram"
* $UCUM#pmol "picomole"
* $UCUM#rad "radian"
* $UCUM#s "second"
* $UCUM#u "Dalton"
* $UCUM#ug "microgram"
* $UCUM#uL "microliter"
* $UCUM#um "micrometer || micron"
* $UCUM#umho "micromhos"
* $UCUM#umol "micromole"
* $UCUM#wk "week"

ValueSet: SplDrugRouteofAdministrationTerminology
Id: spl-drug-route-of-administration-terminology
Title: "Drug Route Of Administration Terminology"
Description: "Terminology used for representation of the information on pharmaceutical product route of administration in the framework of the Structured Product Labeling documents."
* $NCIT#C132737 "Intracanalicular"
* $NCIT#C28161 "INTRAMUSCULAR"
* $NCIT#C38192 "AURICULAR (OTIC)"
* $NCIT#C38193 "BUCCAL"
* $NCIT#C38194 "CONJUNCTIVAL"
* $NCIT#C38197 "DENTAL"
* $NCIT#C38198 "SOFT TISSUE"
* $NCIT#C38200 "HEMODIALYSIS"
* $NCIT#C38203 "IONTOPHORESIS"
* $NCIT#C38205 "ENDOCERVICAL"
* $NCIT#C38206 "ENDOSINUSIAL"
* $NCIT#C38207 "INTRATHORACIC"
* $NCIT#C38208 "ENDOTRACHEAL"
* $NCIT#C38209 "ENTERAL"
* $NCIT#C38210 "EPIDURAL"
* $NCIT#C38211 "EXTRA-AMNIOTIC"
* $NCIT#C38212 "EXTRACORPOREAL"
* $NCIT#C38215 "INFILTRATION"
* $NCIT#C38216 "RESPIRATORY (INHALATION)"
* $NCIT#C38217 "INTRACORONAL, DENTAL"
* $NCIT#C38218 "INTRACORONARY"
* $NCIT#C38219 "INTERSTITIAL"
* $NCIT#C38220 "INTRA-ABDOMINAL"
* $NCIT#C38221 "INTRA-AMNIOTIC"
* $NCIT#C38222 "INTRA-ARTERIAL"
* $NCIT#C38223 "INTRA-ARTICULAR"
* $NCIT#C38224 "INTRABILIARY"
* $NCIT#C38225 "INTRABRONCHIAL"
* $NCIT#C38226 "INTRABURSAL"
* $NCIT#C38227 "INTRACARDIAC"
* $NCIT#C38228 "INTRACARTILAGINOUS"
* $NCIT#C38229 "INTRACAUDAL"
* $NCIT#C38230 "INTRACAVERNOUS"
* $NCIT#C38231 "INTRACAVITARY"
* $NCIT#C38232 "INTRACEREBRAL"
* $NCIT#C38233 "INTRACISTERNAL"
* $NCIT#C38234 "INTRACORNEAL"
* $NCIT#C38235 "INTRACORPORUS CAVERNOSUM"
* $NCIT#C38236 "INTRACRANIAL"
* $NCIT#C38238 "INTRADERMAL"
* $NCIT#C38239 "INTRADISCAL"
* $NCIT#C38240 "INTRADUCTAL"
* $NCIT#C38241 "INTRADUODENAL"
* $NCIT#C38242 "INTRADURAL"
* $NCIT#C38243 "INTRAEPIDERMAL"
* $NCIT#C38245 "INTRAESOPHAGEAL"
* $NCIT#C38246 "INTRAGASTRIC"
* $NCIT#C38247 "INTRAGINGIVAL"
* $NCIT#C38248 "INTRAHEPATIC"
* $NCIT#C38249 "INTRAILEAL"
* $NCIT#C38250 "INTRALESIONAL"
* $NCIT#C38251 "INTRALUMINAL"
* $NCIT#C38252 "INTRALYMPHATIC"
* $NCIT#C38253 "INTRAMEDULLARY"
* $NCIT#C38254 "INTRAMENINGEAL"
* $NCIT#C38255 "INTRAOCULAR"
* $NCIT#C38256 "INTRAOVARIAN"
* $NCIT#C38257 "INTRAPERICARDIAL"
* $NCIT#C38258 "INTRAPERITONEAL"
* $NCIT#C38259 "INTRAPLEURAL"
* $NCIT#C38260 "INTRAPROSTATIC"
* $NCIT#C38261 "INTRAPULMONARY"
* $NCIT#C38262 "INTRASINAL"
* $NCIT#C38263 "INTRASPINAL"
* $NCIT#C38264 "INTRASYNOVIAL"
* $NCIT#C38265 "INTRATENDINOUS"
* $NCIT#C38266 "INTRATESTICULAR"
* $NCIT#C38267 "INTRATHECAL"
* $NCIT#C38268 "INTRATUBULAR"
* $NCIT#C38269 "INTRATUMOR"
* $NCIT#C38270 "INTRATYMPANIC"
* $NCIT#C38271 "URETHRAL"
* $NCIT#C38272 "INTRAUTERINE"
* $NCIT#C38273 "INTRAVASCULAR"
* $NCIT#C38274 "INTRAVENOUS BOLUS"
* $NCIT#C38276 "INTRAVENOUS"
* $NCIT#C38277 "INTRAVENTRICULAR"
* $NCIT#C38278 "INTRAVESICAL"
* $NCIT#C38279 "INTRAVENOUS DRIP"
* $NCIT#C38280 "INTRAVITREAL"
* $NCIT#C38281 "IRRIGATION"
* $NCIT#C38282 "LARYNGEAL"
* $NCIT#C38283 "TRANSMUCOSAL"
* $NCIT#C38284 "NASAL"
* $NCIT#C38285 "NASOGASTRIC"
* $NCIT#C38286 "OCCLUSIVE DRESSING TECHNIQUE"
* $NCIT#C38287 "OPHTHALMIC"
* $NCIT#C38288 "ORAL"
* $NCIT#C38289 "OROPHARYNGEAL"
* $NCIT#C38290 "OTHER"
* $NCIT#C38291 "PARENTERAL"
* $NCIT#C38292 "PERIARTICULAR"
* $NCIT#C38293 "PERINEURAL"
* $NCIT#C38294 "PERIODONTAL"
* $NCIT#C38295 "RECTAL"
* $NCIT#C38296 "RETROBULBAR"
* $NCIT#C38297 "SUBARACHNOID"
* $NCIT#C38298 "SUBCONJUNCTIVAL"
* $NCIT#C38299 "SUBCUTANEOUS"
* $NCIT#C38300 "SUBLINGUAL"
* $NCIT#C38301 "SUBMUCOSAL"
* $NCIT#C38304 "TOPICAL"
* $NCIT#C38305 "TRANSDERMAL"
* $NCIT#C38307 "TRANSPLACENTAL"
* $NCIT#C38308 "TRANSTRACHEAL"
* $NCIT#C38309 "TRANSTYMPANIC"
* $NCIT#C38310 "UNASSIGNED"
* $NCIT#C38311 "UNKNOWN"
* $NCIT#C38312 "URETERAL"
* $NCIT#C38313 "VAGINAL"
* $NCIT#C38633 "ELECTRO-OSMOSIS"
* $NCIT#C38675 "CUTANEOUS"
* $NCIT#C38676 "PERCUTANEOUS"
* $NCIT#C38677 "PERIDURAL"
* $NCIT#C48623 "NOT APPLICABLE"
* $NCIT#C65103 "SUBGINGIVAL"
* $NCIT#C79137 "INTRAMAMMARY"
* $NCIT#C79138 "INTRALINGUAL"
* $NCIT#C79139 "INTRARUMINAL"
* $NCIT#C79141 "INTRANODAL"
* $NCIT#C79142 "INTRAOMENTUM"
* $NCIT#C79143 "SUBRETINAL"
* $NCIT#C79144 "INTRAEPICARDIAL"
* $NCIT#C79145 "TRANSENDOCARDIAL"

ValueSet: GENCcountryCodes
Id: genc-country-codes
Title: "GENC Country Codes"
Description: "The GENC Standard specifies an information model for representing names and codes of geopolitical entities and administrative subdivisions, with supporting information. A geopolitical entity is a region controlled by a political community having an organized government and possessing internal and external sovereignty, most often as a State but sometimes having a dependent relationship on another political authority, or a special sovereignty status. Geopolitical entities may be divided into administratively subordinate divisions. A GENC code (or, synonymously, an ISO 3166 code element) for a geopolitical entity or administrative subdivision is a unique designation of that concept within a set of similar concepts established by a suitable authority. This information model is based on that of ISO 3166 but extended to capture additional information required by U.S. Government stakeholders."

* $GENC#AFG "AFGHANISTAN"
* $GENC#XQZ "AKROTIRI"
* $GENC#ALB "ALBANIA"
* $GENC#DZA "ALGERIA"
* $GENC#ASM "AMERICAN SAMOA"
* $GENC#AND "ANDORRA"
* $GENC#AGO "ANGOLA"
* $GENC#AIA "ANGUILLA"
* $GENC#ATA "ANTARCTICA"
* $GENC#ATG "ANTIGUA AND BARBUDA"
* $GENC#ARG "ARGENTINA"
* $GENC#ARM "ARMENIA"
* $GENC#ABW "ARUBA"
* $GENC#XAC "ASHMORE AND CARTIER ISLANDS"
* $GENC#AUS "AUSTRALIA"
* $GENC#AUT "AUSTRIA"
* $GENC#AZE "AZERBAIJAN"
* $GENC#BHS "BAHAMAS, THE"
* $GENC#BHR "BAHRAIN"
* $GENC#XBK "BAKER ISLAND"
* $GENC#BGD "BANGLADESH"
* $GENC#BRB "BARBADOS"
* $GENC#XBI "BASSAS DA INDIA"
* $GENC#BLR "BELARUS"
* $GENC#BEL "BELGIUM"
* $GENC#BLZ "BELIZE"
* $GENC#BEN "BENIN"
* $GENC#BMU "BERMUDA"
* $GENC#BTN "BHUTAN"
* $GENC#BOL "BOLIVIA"
* $GENC#BES "BONAIRE, SINT EUSTATIUS, AND SABA"
* $GENC#BIH "BOSNIA AND HERZEGOVINA"
* $GENC#BWA "BOTSWANA"
* $GENC#BVT "BOUVET ISLAND"
* $GENC#BRA "BRAZIL"
* $GENC#IOT "BRITISH INDIAN OCEAN TERRITORY"
* $GENC#BRN "BRUNEI"
* $GENC#BGR "BULGARIA"
* $GENC#BFA "BURKINA FASO"
* $GENC#MMR "BURMA"
* $GENC#BDI "BURUNDI"
* $GENC#CPV "CABO VERDE"
* $GENC#KHM "CAMBODIA"
* $GENC#CMR "CAMEROON"
* $GENC#CAN "CANADA"
* $GENC#CYM "CAYMAN ISLANDS"
* $GENC#CAF "CENTRAL AFRICAN REPUBLIC"
* $GENC#TCD "CHAD"
* $GENC#CHL "CHILE"
* $GENC#CHN "CHINA"
* $GENC#CXR "CHRISTMAS ISLAND"
* $GENC#CPT "CLIPPERTON ISLAND"
* $GENC#CCK "COCOS (KEELING) ISLANDS"
* $GENC#COL "COLOMBIA"
* $GENC#COM "COMOROS"
* $GENC#COG "CONGO (BRAZZAVILLE)"
* $GENC#COD "CONGO (KINSHASA)"
* $GENC#COK "COOK ISLANDS"
* $GENC#XCS "CORAL SEA ISLANDS"
* $GENC#CRI "COSTA RICA"
* $GENC#CIV "CÔTE D'IVOIRE"
* $GENC#HRV "CROATIA"
* $GENC#CUB "CUBA"
* $GENC#CUW "CURAÇAO"
* $GENC#CYP "CYPRUS"
* $GENC#CZE "CZECHIA"
* $GENC#DNK "DENMARK"
* $GENC#XXD "DHEKELIA"
* $GENC#DGA "DIEGO GARCIA"
* $GENC#DJI "DJIBOUTI"
* $GENC#DMA "DOMINICA"
* $GENC#DOM "DOMINICAN REPUBLIC"
* $GENC#ECU "ECUADOR"
* $GENC#EGY "EGYPT"
* $GENC#SLV "EL SALVADOR"
* $GENC#XAZ "ENTITY 1"
* $GENC#XCR "ENTITY 2"
* $GENC#XCY "ENTITY 3"
* $GENC#XKM "ENTITY 4"
* $GENC#XKN "ENTITY 5"
* $GENC#AX3 "ENTITY 6"
* $GENC#GNQ "EQUATORIAL GUINEA"
* $GENC#ERI "ERITREA"
* $GENC#EST "ESTONIA"
* $GENC#ETH "ETHIOPIA"
* $GENC#XEU "EUROPA ISLAND"
* $GENC#FLK "FALKLAND ISLANDS (ISLAS MALVINAS)"
* $GENC#FRO "FAROE ISLANDS"
* $GENC#FJI "FIJI"
* $GENC#FIN "FINLAND"
* $GENC#FRA "FRANCE"
* $GENC#GUF "FRENCH GUIANA"
* $GENC#PYF "FRENCH POLYNESIA"
* $GENC#ATF "FRENCH SOUTHERN AND ANTARCTIC LANDS"
* $GENC#GAB "GABON"
* $GENC#GMB "GAMBIA, THE"
* $GENC#XGZ "GAZA STRIP"
* $GENC#GEO "GEORGIA"
* $GENC#DEU "GERMANY"
* $GENC#GHA "GHANA"
* $GENC#GIB "GIBRALTAR"
* $GENC#XGL "GLORIOSO ISLANDS"
* $GENC#GRC "GREECE"
* $GENC#GRL "GREENLAND"
* $GENC#GRD "GRENADA"
* $GENC#GLP "GUADELOUPE"
* $GENC#GUM "GUAM"
* $GENC#AX2 "GUANTANAMO BAY NAVAL BASE"
* $GENC#GTM "GUATEMALA"
* $GENC#GGY "GUERNSEY"
* $GENC#GIN "GUINEA"
* $GENC#GNB "GUINEA-BISSAU"
* $GENC#GUY "GUYANA"
* $GENC#HTI "HAITI"
* $GENC#HMD "HEARD ISLAND AND MCDONALD ISLANDS"
* $GENC#HND "HONDURAS"
* $GENC#HKG "HONG KONG"
* $GENC#XHO "HOWLAND ISLAND"
* $GENC#HUN "HUNGARY"
* $GENC#ISL "ICELAND"
* $GENC#IND "INDIA"
* $GENC#IDN "INDONESIA"
* $GENC#IRN "IRAN"
* $GENC#IRQ "IRAQ"
* $GENC#IRL "IRELAND"
* $GENC#IMN "ISLE OF MAN"
* $GENC#ISR "ISRAEL"
* $GENC#ITA "ITALY"
* $GENC#JAM "JAMAICA"
* $GENC#XJM "JAN MAYEN"
* $GENC#JPN "JAPAN"
* $GENC#XJV "JARVIS ISLAND"
* $GENC#JEY "JERSEY"
* $GENC#XJA "JOHNSTON ATOLL"
* $GENC#JOR "JORDAN"
* $GENC#XJN "JUAN DE NOVA ISLAND"
* $GENC#KAZ "KAZAKHSTAN"
* $GENC#KEN "KENYA"
* $GENC#XKR "KINGMAN REEF"
* $GENC#KIR "KIRIBATI"
* $GENC#PRK "KOREA, NORTH"
* $GENC#KOR "KOREA, SOUTH"
* $GENC#XKS "KOSOVO"
* $GENC#KWT "KUWAIT"
* $GENC#KGZ "KYRGYZSTAN"
* $GENC#LAO "LAOS"
* $GENC#LVA "LATVIA"
* $GENC#LBN "LEBANON"
* $GENC#LSO "LESOTHO"
* $GENC#LBR "LIBERIA"
* $GENC#LBY "LIBYA"
* $GENC#LIE "LIECHTENSTEIN"
* $GENC#LTU "LITHUANIA"
* $GENC#LUX "LUXEMBOURG"
* $GENC#MAC "MACAU"
* $GENC#MKD "NORTH MACEDONIA"
* $GENC#MDG "MADAGASCAR"
* $GENC#MWI "MALAWI"
* $GENC#MYS "MALAYSIA"
* $GENC#MDV "MALDIVES"
* $GENC#MLI "MALI"
* $GENC#MLT "MALTA"
* $GENC#MHL "MARSHALL ISLANDS"
* $GENC#MTQ "MARTINIQUE"
* $GENC#MRT "MAURITANIA"
* $GENC#MUS "MAURITIUS"
* $GENC#MYT "MAYOTTE"
* $GENC#MEX "MEXICO"
* $GENC#FSM "MICRONESIA, FEDERATED STATES OF"
* $GENC#XMW "MIDWAY ISLANDS"
* $GENC#MDA "MOLDOVA"
* $GENC#MCO "MONACO"
* $GENC#MNG "MONGOLIA"
* $GENC#MNE "MONTENEGRO"
* $GENC#MSR "MONTSERRAT"
* $GENC#MAR "MOROCCO"
* $GENC#MOZ "MOZAMBIQUE"
* $GENC#NAM "NAMIBIA"
* $GENC#NRU "NAURU"
* $GENC#XNV "NAVASSA ISLAND"
* $GENC#NPL "NEPAL"
* $GENC#NLD "NETHERLANDS"
* $GENC#NCL "NEW CALEDONIA"
* $GENC#NZL "NEW ZEALAND"
* $GENC#NIC "NICARAGUA"
* $GENC#NER "NIGER"
* $GENC#NGA "NIGERIA"
* $GENC#NIU "NIUE"
* $GENC#NFK "NORFOLK ISLAND"
* $GENC#MNP "NORTHERN MARIANA ISLANDS"
* $GENC#NOR "NORWAY"
* $GENC#OMN "OMAN"
* $GENC#PAK "PAKISTAN"
* $GENC#PLW "PALAU"
* $GENC#XPL "PALMYRA ATOLL"
* $GENC#PAN "PANAMA"
* $GENC#PNG "PAPUA NEW GUINEA"
* $GENC#XPR "PARACEL ISLANDS"
* $GENC#PRY "PARAGUAY"
* $GENC#PER "PERU"
* $GENC#PHL "PHILIPPINES"
* $GENC#PCN "PITCAIRN ISLANDS"
* $GENC#POL "POLAND"
* $GENC#PRT "PORTUGAL"
* $GENC#PRI "PUERTO RICO"
* $GENC#QAT "QATAR"
* $GENC#REU "REUNION"
* $GENC#ROU "ROMANIA"
* $GENC#RUS "RUSSIA"
* $GENC#RWA "RWANDA"
* $GENC#BLM "SAINT BARTHELEMY"
* $GENC#SHN "SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA"
* $GENC#KNA "SAINT KITTS AND NEVIS"
* $GENC#LCA "SAINT LUCIA"
* $GENC#MAF "SAINT MARTIN"
* $GENC#SPM "SAINT PIERRE AND MIQUELON"
* $GENC#VCT "SAINT VINCENT AND THE GRENADINES"
* $GENC#WSM "SAMOA"
* $GENC#SMR "SAN MARINO"
* $GENC#STP "SAO TOME AND PRINCIPE"
* $GENC#SAU "SAUDI ARABIA"
* $GENC#SEN "SENEGAL"
* $GENC#SRB "SERBIA"
* $GENC#SYC "SEYCHELLES"
* $GENC#SLE "SIERRA LEONE"
* $GENC#SGP "SINGAPORE"
* $GENC#SXM "SINT MAARTEN"
* $GENC#SVK "SLOVAKIA"
* $GENC#SVN "SLOVENIA"
* $GENC#SLB "SOLOMON ISLANDS"
* $GENC#SOM "SOMALIA"
* $GENC#ZAF "SOUTH AFRICA"
* $GENC#SGS "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS"
* $GENC#SSD "SOUTH SUDAN"
* $GENC#ESP "SPAIN"
* $GENC#XSP "SPRATLY ISLANDS"
* $GENC#LKA "SRI LANKA"
* $GENC#SDN "SUDAN"
* $GENC#SUR "SURINAME"
* $GENC#XSV "SVALBARD"
* $GENC#SWZ "ESWATINI"
* $GENC#SWE "SWEDEN"
* $GENC#CHE "SWITZERLAND"
* $GENC#SYR "SYRIA"
* $GENC#TWN "TAIWAN"
* $GENC#TJK "TAJIKISTAN"
* $GENC#TZA "TANZANIA"
* $GENC#THA "THAILAND"
* $GENC#TLS "TIMOR-LESTE"
* $GENC#TGO "TOGO"
* $GENC#TKL "TOKELAU"
* $GENC#TON "TONGA"
* $GENC#TTO "TRINIDAD AND TOBAGO"
* $GENC#XTR "TROMELIN ISLAND"
* $GENC#TUN "TUNISIA"
* $GENC#TUR "TURKEY"
* $GENC#TKM "TURKMENISTAN"
* $GENC#TCA "TURKS AND CAICOS ISLANDS"
* $GENC#TUV "TUVALU"
* $GENC#UGA "UGANDA"
* $GENC#UKR "UKRAINE"
* $GENC#ARE "UNITED ARAB EMIRATES"
* $GENC#GBR "UNITED KINGDOM"
* $GENC#USA "UNITED STATES"
* $GENC#AX1 "UNKNOWN"
* $GENC#URY "URUGUAY"
* $GENC#UZB "UZBEKISTAN"
* $GENC#VUT "VANUATU"
* $GENC#VAT "VATICAN CITY"
* $GENC#VEN "VENEZUELA"
* $GENC#VNM "VIETNAM"
* $GENC#VGB "VIRGIN ISLANDS, BRITISH"
* $GENC#VIR "VIRGIN ISLANDS, U.S."
* $GENC#XWK "WAKE ISLAND"
* $GENC#WLF "WALLIS AND FUTUNA"
* $GENC#XWB "WEST BANK"
* $GENC#ESH "WESTERN SAHARA"
* $GENC#YEM "YEMEN"
* $GENC#ZMB "ZAMBIA"
* $GENC#ZWE "ZIMBABWE"



