ValueSet: ApplicationSubmissionType
Id: valuset-ApplicationSubmissionType
Title: "PQ/CMC Application Submission Type Terminology"
Description: "Terminology used to qualify the information pertaining to application submission types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* ^jurisdiction = urn:iso:std:iso:3166#840 
* $NCI-T#C176802 "Amendment to INDs"
* $NCI-T#C176803 "Amendment to Master Files"
* $NCI-T#C176796 "Amendment to Original"
* $NCI-T#C176798 "Amendment to Supplement"
* $NCI-T#C70860 "Original"
* $NCI-T#C176797 "Supplement to Original"

ValueSet: ApplicationType
Id: valuset-ApplicationType
Title: "PQ/CMC Application Type Terminology"
Description: "Terminology used to qualify the information pertaining to application types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* ^jurisdiction = urn:iso:std:iso:3166#840 
* $NCI-T#C115123 "Abbreviated New Animal Drug Application"
* $NCI-T#C73113 "Abbreviated New Drug Application"
* $NCI-T#C71778 "Biologics License Application"
* $NCI-T#C115122 "Generic Investigational New Animal Drug File"
* $NCI-T#C80440 "Humanitarian Device Exemption (HDE)"
* $NCI-T#C82667 "Investigational Device Exemption"
* $NCI-T#C96091 "Investigational New Animal Drug File"
* $NCI-T#C96090 "Investigational New Drug Application"
* $NCI-T#C70877 "Master File"
* $NCI-T#C96092 "New Active Ingredient"
* $NCI-T#C72901 "New Animal Drug Application"
* $NCI-T#C72899 "New Drug Application"
* $NCI-T#C70880 "Premarket Approval"
* $NCI-T#C80442 "Premarket Notification 510(K)"

ValueSet: BatchUtilization
Id: valuset-BatchUtilization
Title: "PQ/CMC Batch Utilization Terminology"
Description: "Terminology used to qualify the information pertaining to batch utilization in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* ^jurisdiction = urn:iso:std:iso:3166#840 
* $NCI-T#C133994 "Bioequivalence"
* $NCI-T#C133992 "Clinical"
* $NCI-T#C133990 "Commercial"
* $NCI-T#C133991 "Development"
* $NCI-T#C133993 "Validation"

ValueSet: ChemicalStructureDataFileOrigin
Id: valuset-ChemicalStructureDataFileOrigin
Title: "PQ/CMC Chemical Structure Data File Origin Terminology"
Description: "Terminology used to qualify the information pertaining to chemical structure data file origins in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C16275 "Calculated"
* $NCI-T#C133995 "Experimental"

ValueSet: ChemicalStructureDataFileType
Id: valuset-ChemicalStructureDataFileType
Title: "PQ/CMC Chemical Structure Data File Type Terminology"
Description: "Terminology used to qualify the information pertaining to chemical structure data file types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C54683 "InChI File (small molecule)"
* $NCI-T#C133997 "mmCIF (large molecules)"
* $NCI-T#C133910 "MOLFILE"
* $NCI-T#C49039 "PDB"
* $NCI-T#C133996 "SDF"
* $NCI-T#C54684 "SMILES"

ValueSet: ClosureType
Id: valuset-ClosureType
Title: "PQ/CMC Closure Type Terminology"
Description: "Terminology used to qualify the information pertaining to closure types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C96113 "Child-resistant, Metal"
* $NCI-T#C96114 "Child-resistant, Plastic"
* $NCI-T#C96115 "Continuous Thread, Metal"
* $NCI-T#C96116 "Continuous Thread, Plastic"
* $NCI-T#C96125 "Crown, Metal"
* $NCI-T#C96128 "Flip-Top (Dispensing), Plastic"
* $NCI-T#C96129 "Hinged (Dispensing), Plastic"
* $NCI-T#C96130 "Linerless, Plastic"
* $NCI-T#C96126 "Lug, Metal"
* $NCI-T#C96124 "Press-on, Composite"
* $NCI-T#C96123 "Press-on/twist-off, Metal"
* $NCI-T#C96131 "Pump (Dispensing), Plastic"
* $NCI-T#C96132 "Push-pull (Dispensing), Plastic"
* $NCI-T#C96127 "Roll-on, Metal"
* $NCI-T#C96133 "Snap-on Cap, Plastic"
* $NCI-T#C96134 "Snip-tip (Dispensing), Plastic"
* $NCI-T#C96139 "Stopper"
* $NCI-T#C96120 "Tamper-evident, Composite"
* $NCI-T#C96117 "Tamper-evident, Metal"
* $NCI-T#C96118 "Tamper-evident, Plastic"
* $NCI-T#C96140 "Tie"
* $NCI-T#C96135 "Toggle-swing (Dispensing), Plastic"
* $NCI-T#C96136 "Trigger Sprayer (Dispensing), Plastic"
* $NCI-T#C96137 "Twist Open/Close (Dispensing), Plastic"
* $NCI-T#C96122 "Vacuum, Composite"
* $NCI-T#C96119 "Vacuum, Metal"
* $NCI-T#C96121 "Vacuum, Plastic"
* $NCI-T#C96138 "Valved (Dispensing), Plastic"

ValueSet: ConformancetoCriteria
Id: valuset-ConformancetoCriteria
Title: "PQ/CMC Conformance to Criteria Terminology"
Description: "Terminology used to qualify the information pertaining to conformance to criteria in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C80262 "Conforms"
* $NCI-T#C133998 "Does not conform"

ValueSet: ContainerOrientation
Id: valuset-ContainerOrientation
Title: "PQ/CMC Container Orientation Terminology"
Description: "Terminology used to qualify the information pertaining to container orientation in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C25241 "Horizontal"
* $NCI-T#C133999 "Inverted"
* $NCI-T#C86043 "Upright"
* $NCI-T#C133915 "Valve-down"
* $NCI-T#C133914 "Valve-up"

ValueSet: ContainerType
Id: valuset-ContainerType
Title: "PQ/CMC Container Type Terminology"
Description: "Terminology used to qualify the information pertaining to container types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C43165 "AMPULE"
* $NCI-T#C43166 "APPLICATOR"
* $NCI-T#C43167 "BAG"
* $NCI-T#C43168 "BLISTER PACK"
* $NCI-T#C43169 "BOTTLE"
* $NCI-T#C43170 "BOTTLE, DISPENSING"
* $NCI-T#C43171 "BOTTLE, DROPPER"
* $NCI-T#C43172 "BOTTLE, GLASS"
* $NCI-T#C43173 "BOTTLE, PLASTIC"
* $NCI-T#C43174 "BOTTLE, PUMP"
* $NCI-T#C43175 "BOTTLE, SPRAY"
* $NCI-T#C43176 "BOTTLE, UNIT-DOSE"
* $NCI-T#C43177 "BOTTLE, WITH APPLICATOR"
* $NCI-T#C43178 "BOX"
* $NCI-T#C43179 "BOX, UNIT-DOSE"
* $NCI-T#C43180 "CAN"
* $NCI-T#C43181 "CANISTER"
* $NCI-T#C96143 "Canisters, lined"
* $NCI-T#C92708 "CAPSULE"
* $NCI-T#C43182 "CARTON"
* $NCI-T#C43183 "CARTRIDGE"
* $NCI-T#C43184 "CASE"
* $NCI-T#C43185 "CELLO PACK"
* $NCI-T#C43186 "CONTAINER"
* $NCI-T#C43187 "CUP"
* $NCI-T#C43188 "CUP, UNIT-DOSE"
* $NCI-T#C43189 "CYLINDER"
* $NCI-T#C43190 "DEWAR"
* $NCI-T#C43191 "DIALPACK"
* $NCI-T#C96141 "Dish, Petri"
* $NCI-T#C43192 "DOSE PACK"
* $NCI-T#C43193 "DRUM"
* $NCI-T#C96144 "Flask"
* $NCI-T#C79135 "FLEXIBLE INTERMEDIATE BULK CONTAINER"
* $NCI-T#C16738 "INHALER"
* $NCI-T#C43194 "INHALER, REFILL"
* $NCI-T#C43195 "JAR"
* $NCI-T#C43196 "JUG"
* $NCI-T#C43197 "KIT"
* $NCI-T#C48626 "NOT STATED"
* $NCI-T#C43233 "PACKAGE"
* $NCI-T#C43198 "PACKAGE, COMBINATION"
* $NCI-T#C43199 "PACKET"
* $NCI-T#C79136 "PAIL"
* $NCI-T#C82332 "PATCH"
* $NCI-T#C96142 "Plate, Microwell"
* $NCI-T#C43200 "POUCH"
* $NCI-T#C43201 "SUPERSACK"
* $NCI-T#C43202 "SYRINGE"
* $NCI-T#C43203 "SYRINGE, GLASS"
* $NCI-T#C43204 "SYRINGE, PLASTIC"
* $NCI-T#C43205 "TABMINDER"
* $NCI-T#C43206 "TANK"
* $NCI-T#C53438 "TRAY"
* $NCI-T#C42794 "TUBE"
* $NCI-T#C43207 "TUBE, WITH APPLICATOR"
* $NCI-T#C43226 "VIAL"
* $NCI-T#C43208 "VIAL, DISPENSING"
* $NCI-T#C43209 "VIAL, GLASS"
* $NCI-T#C43210 "VIAL, MULTI-DOSE"
* $NCI-T#C43211 "VIAL, PATENT DELIVERY SYSTEM"
* $NCI-T#C43212 "VIAL, PHARMACY BULK PACKAGE"
* $NCI-T#C43213 "VIAL, PIGGYBACK"
* $NCI-T#C43214 "VIAL, PLASTIC"
* $NCI-T#C43215 "VIAL, SINGLE-DOSE"
* $NCI-T#C43216 "VIAL, SINGLE-USE"

ValueSet: CoPackagedIndicator
Id: valuset-CoPackagedIndicator
Title: "PQ/CMC Co-Packaged Indicator Terminology"
Description: "Terminology used to qualify the information pertaining to co-packaged indicators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C49487 "No"
* $NCI-T#C49488 "Yes"

ValueSet: DrugProductComponentFunctionCategory
Id: valuset-DrugProductComponentFunctionCategory
Title: "PQ/CMC Drug Product Component Function Category Terminology"
Description: "Terminology used to qualify the information pertaining to drug product component function categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C82533 "Active Ingredient"
* $NCI-T#C2140 "Adjuvant"
* $NCI-T#C42637 "Inactive Ingredient"

ValueSet: DrugSubstanceProductIndicator
Id: valuset-DrugSubstanceProductIndicator
Title: "PQ/CMC Drug Substance Product Indicator Terminology"
Description: "Terminology used to qualify the information pertaining to drug substance product indicators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C1909 "Product"
* $NCI-T#C45306 "SUBSTANCE"

ValueSet: ExcipientFunction
Id: valuset-ExcipientFunction
Title: "PQ/CMC Excipient Function Terminology"
Description: "Terminology used to qualify the information pertaining to excipient functions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C176637 "Absorption modifier"
* $NCI-T#C89528 "Adhesive"
* $NCI-T#C176642 "Adsorbent"
* $NCI-T#C176643 "Air displacement"
* $NCI-T#C42654 "Anticaking agent"
* $NCI-T#C275 "Antioxidant"
* $NCI-T#C42647 "Binder"
* $NCI-T#C70815 "Buffering agent"
* $NCI-T#C176644 "Bulking agent"
* $NCI-T#C92708 "CAPSULE"
* $NCI-T#C176645 "Carrier"
* $NCI-T#C360 "Chelating agent"
* $NCI-T#C42656 "Coloring agent"
* $NCI-T#C176646 "Complexing agent"
* $NCI-T#C53306 "Cryoprotectant"
* $NCI-T#C176647 "Denaturant"
* $NCI-T#C42648 "Disintegrant"
* $NCI-T#C42662 "Dispersing agent"
* $NCI-T#C176638 "Effervescent agent"
* $NCI-T#C176632 "Emollient"
* $NCI-T#C73477 "Emulsifying Excipient"
* $NCI-T#C176633 "Emulsion stabilizing agent"
* $NCI-T#C42650 "Filler"
* $NCI-T#C176648 "Film coating agent"
* $NCI-T#C176634 "Foam stabilizing agent"
* $NCI-T#C176649 "Free radical scavenger"
* $NCI-T#C176650 "Gelling agent"
* $NCI-T#C176651 "Humectant"
* $NCI-T#C42657 "Ink"
* $NCI-T#C42653 "Lubricant"
* $NCI-T#C176652 "Lyophilization aid"
* $NCI-T#C176653 "Matrix-forming agent"
* $NCI-T#C176654 "Microencapsulating agent"
* $NCI-T#C176655 "Ointment base"
* $NCI-T#C176656 "Opacifier"
* $NCI-T#C176635 "Organoleptic agent"
* $NCI-T#C176657 "Osmotic agent"
* $NCI-T#C176658 "pH modifier"
* $NCI-T#C55826 "Plasticizer"
* $NCI-T#C176659 "Polishing agent"
* $NCI-T#C176660 "Polymers for ophthalmic use"
* $NCI-T#C42659 "Preservative"
* $NCI-T#C176661 "Propellant"
* $NCI-T#C176639 "Reducing agent"
* $NCI-T#C176662 "Release modifying agent"
* $NCI-T#C176640 "Solubilizing agent"
* $NCI-T#C45790 "Solvent"
* $NCI-T#C176636 "Stabilizer"
* $NCI-T#C176663 "Suppository base"
* $NCI-T#C42739 "Surfactant"
* $NCI-T#C42660 "Suspending agent"
* $NCI-T#C176641 "Tonicity agent"
* $NCI-T#C176664 "Transdermal delivery component"
* $NCI-T#C176665 "Transfer ligand"
* $NCI-T#C927 "Vehicle"
* $NCI-T#C176666 "Viscosity modifier"
* $NCI-T#C176667 "Water-repelling agent"
* $NCI-T#C176668 "Wetting agent"

ValueSet: ImpurityClassification
Id: valuset-ImpurityClassification
Title: "PQ/CMC Impurity Classification Terminology"
Description: "Terminology used to qualify the information pertaining to impurity classifications in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C84280 "Contaminants"
* $NCI-T#C176812 "Process Related"
* $NCI-T#C176813 "Product Related"

ValueSet: InterpretationCodeNumeric
Id: valuset-InterpretationCodeNumeric
Title: "PQ/CMC Interpretation Code (numeric) Terminology"
Description: "Terminology used to qualify the information pertaining to numeric interpretation codes in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C48793 "EQ"
* $NCI-T#C61585 "LT (less than)"
* $NCI-T#C61584 "MT (more than)"
* $NCI-T#C61583 "NLT (not less than)"
* $NCI-T#C61586 "NMT (not more than)"
* $NCI-T#C48660 "Not Applicable"

ValueSet: InterpretationCodeText
Id: valuset-InterpretationCodeText
Title: "PQ/CMC Interpretation Code (text) Terminology"
Description: "Terminology used to qualify the information pertaining to textual interpretation codes in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C48660 "Not Applicable"

ValueSet: ProcessRelatedImpurityCategory
Id: valuset-ProcessRelatedImpurityCategory
Title: "PQ/CMC Process Related Impurity Category Terminology"
Description: "Terminology used to qualify the information pertaining to process related impurity categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C134001 "Inorganic"
* $NCI-T#C134000 "Organic"
* $NCI-T#C176815 "Residual Solvent"

ValueSet: ProductRelatedImpurityCategory
Id: valuset-ProductRelatedImpurityCategory
Title: "PQ/CMC Product Related Impurity Category Terminology"
Description: "Terminology used to qualify the information pertaining to product related impurity categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C176816 "Degradants"
* $NCI-T#C176813 "Product Related"

ValueSet: QualityBenchmark
Id: valuset-QualityBenchmark
Title: "PQ/CMC Quality Benchmark Terminology"
Description: "Terminology used to qualify the information pertaining to quality benchmarks in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C176793 "BP"
* $NCI-T#C134009 "Company Standard"
* $NCI-T#C134007 "EP"
* $NCI-T#C134008 "JP"
* $NCI-T#C134006 "USP-NF"

ValueSet: SourceType
Id: valuset-SourceType
Title: "PQ/CMC Source Type Terminology"
Description: "Terminology used to qualify the information pertaining to source types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C14182 "Animal"
* $NCI-T#C18634 "Animal-derived indirectly"
* $NCI-T#C48807 "Chemical"
* $NCI-T#C14225 "Human"
* $NCI-T#C14227 "Insect"
* $NCI-T#C14329 "Microbial"
* $NCI-T#C14258 "Plant"

ValueSet: SpecificationStatus
Id: valuset-SpecificationStatus
Title: "PQ/CMC Specification Status Terminology"
Description: "Terminology used to qualify the information pertaining to specification statuses in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C25425 "Approved"
* $NCI-T#C48660 "Not Applicable"
* $NCI-T#C134011 "Not Approved"
* $NCI-T#C134012 "Reported in a CBE or AR"
* $NCI-T#C134010 "Tentatively Approved"

ValueSet: SpecificationType
Id: valuset-SpecificationType
Title: "PQ/CMC Specification Type Terminology"
Description: "Terminology used to qualify the information pertaining to specification types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"

* $NCI-T#C134021 "Drug Product"
* $NCI-T#C134022 "Drug Substance"
* $NCI-T#C133931 "Raw Materials/Excipients/Intermediates/Reagents"

ValueSet: SponsorIdentifierType
Id: valuset-SponsorIdentifierType
Title: "PQ/CMC Sponsor Identifier Type Terminology"
Description: "Terminology used to qualify the information pertaining to sponsor identifier types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C134005 "CFN"
* $NCI-T#C134003 "DUNS"
* $NCI-T#C134004 "FEI"
* $NCI-T#C17998 "Unknown"

ValueSet: StorageConditions
Id: valuset-StorageConditions
Title: "PQ/CMC Storage Conditions Terminology"
Description: "Terminology used to qualify the information pertaining to storage conditions in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C133936 "-20 +/- 5 degrees C"
* $NCI-T#C134018 "25 +/- 2 degrees C/40% +/- 5%RH"
* $NCI-T#C134014 "25 +/- 2 degrees C/60% +/- 5%RH"
* $NCI-T#C134015 "30 +/- 2 degrees C/65% +/- 5%RH"
* $NCI-T#C134017 "30 +/- 2 degrees C/75% +/- 5%RH"
* $NCI-T#C134019 "30 degrees C +/- 2 degrees C/35%RH +/- 5%RH"
* $NCI-T#C134016 "40 +/- 2 degrees C/75% +/- 5%RH"
* $NCI-T#C133940 "40 degrees C +/- 2 degrees C/not more than (NMT) 25%RH"
* $NCI-T#C133935 "5 +/- 3 degrees C"
* $NCI-T#C96148 "Proprietary"

ValueSet: StrengthOperator
Id: valuset-StrengthOperator
Title: "PQ/CMC Strength Operator Terminology"
Description: "Terminology used to qualify the information pertaining to strength operators in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C48793 "EQ"
* $NCI-T#C61585 "LT (less than)"
* $NCI-T#C61584 "MT (more than)"
* $NCI-T#C61583 "NLT (not less than)"
* $NCI-T#C61586 "NMT (not more than)"
* $NCI-T#C48660 "Not Applicable"

ValueSet: StrengthType
Id: valuset-StrengthType
Title: "PQ/CMC Strength Type Terminology"
Description: "Terminology used to qualify the information pertaining to strength types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C45420 "Activity"
* $NCI-T#C168628 "Mass"

ValueSet: TestCategory
Id: valuset-TestCategory
Title: "PQ/CMC Test Category Terminology"
Description: "Terminology used to qualify the information pertaining to test categories in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C60819 "Assay"
* $NCI-T#C158425 "Biological Properties"
* $NCI-T#C138990 "Description"
* $NCI-T#C138993 "Identification"
* $NCI-T#C158423 "Impurities"
* $NCI-T#C176810 "Microbiological Properties"
* $NCI-T#C176811 "Physico-Chemical Properties"

ValueSet: TestingSiteUniqueIdentifierType
Id: valuset-TestingSiteUniqueIdentifierType
Title: "PQ/CMC Test Method Origin Terminology"
Description: "Terminology used to qualify the information pertaining to test method origins in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C134005 "CFN"
* $NCI-T#C134003 "DUNS"
* $NCI-T#C134004 "FEI"
* $NCI-T#C17998 "Unknown"

ValueSet: TestMethodOrigin
Id: valuset-TestMethodOrigin
Title: "PQ/CMC Test Usage Terminology"
Description: "Terminology used to qualify the information pertaining to test usage in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C96164 "CFR"
* $NCI-T#C96102 "Compendial"
* $NCI-T#C96103 "Proprietary"

ValueSet: TestUsage
Id: valuset-TestUsage
Title: "PQ/CMC Testing Site Unique Identifier Type Terminology"
Description: "Terminology used to qualify the information pertaining to testing site unique identifier types in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* ^publisher = "Food and Drug Administration (FDA) and the National Cancer Institute's Thesaurus (NCIt)"
* $NCI-T#C134029 "Release"
* $NCI-T#C134030 "Stability"

ValueSet: UnitsofMeasure
Id: valuset-UnitsofMeasure
Title: "PQ/CMC Units of Measure Terminology"
Description: "Terminology used to qualify the information pertaining to units of measure in the framework of the Pharmaceutical Quality/Chemistry, Manufacturing and Controls documents."
* $UCUM#% "percent"
* $UCUM#%{VolumeToVolume} "percent volume per volume"
* $UCUM#%{WeightToVolume} "percent weight per volume"
* $UCUM#%{WeightToWeight} "percent weight/weight"
* $UCUM#(m2.d) "meter squared in 24 hours"
* $UCUM#[Btu] "British Thermal Unit"
* $UCUM#[CFU] "colony forming units"
* $UCUM#[degF] "degree Fahrenheit"
* $UCUM#[EU] "Ehrlich unit"
* $UCUM#[in_i] "inch"
* $UCUM#[IU] "international unit"
* $UCUM#[lb_av] "pound"
* $UCUM#[lbf_av] "pound foot"
* $UCUM#[oz_av] "ounce"
* $UCUM#[pH] "pH"
* $UCUM#[ppb] "parts per billion"
* $UCUM#[ppm] "parts per million"
* $UCUM#[ppth] "parts per thousand"
* $UCUM#[pptr] "parts per trillion"
* $UCUM#[psi] "pounds per square inch"
* $UCUM#[pt_us] "pints (US Dry)"
* $UCUM#[qt_us] "quarts (US Dry)"
* $UCUM#{actuation} "actuation"
* $UCUM#{can} "can"
* $UCUM#{tbl} "tablet"
* $UCUM#{tot} "particles"
* $UCUM#{vial} "vial"
* $UCUM#a "year"
* $UCUM#Cel "degree Celsius"
* $UCUM#cm "centimeter"
//* $UCUM#cm3 || mL "cubic centimeter || mililiter || milliliter"
* $UCUM#d "day"
* $UCUM#deg "degrees to rotation"
* $UCUM#g "gram"
* $UCUM#gal "gallon"
* $UCUM#h "hour"
* $UCUM#K "degree Kelvin"
* $UCUM#kg "kilogram"
* $UCUM#kgf "kilopond"
* $UCUM#ku "kiloDalton"
* $UCUM#L "liter"
* $UCUM#m "meter"
* $UCUM#m2 "square meter"
* $UCUM#m3 "cubic meter"
* $UCUM#mg "milligram"
* $UCUM#mg% "milligram per 100 milliliters of solution"
* $UCUM#min "minute"
* $UCUM#mm "millimeter"
* $UCUM#mmol "millimole"
* $UCUM#mo "month"
* $UCUM#mol "mole"
* $UCUM#mosm "milliosmole"
* $UCUM#ms "millisiemens"
* $UCUM#N "Newton"
* $UCUM#ng "nanogram"
* $UCUM#nm "nanometer"
* $UCUM#nmol "nanomole"
* $UCUM#pg "picogram"
* $UCUM#pmol "picomole"
* $UCUM#rad "radian"
* $UCUM#s "second"
* $UCUM#u "Dalton"
* $UCUM#u "atomic mass unit"
* $UCUM#U "catalytic activity unit"
* $UCUM#ug "microgram"
* $UCUM#uL "microliter"
* $UCUM#um "micrometer || micron"
* $UCUM#umho "micromhos"
* $UCUM#umol "micromole"
* $UCUM#wk "week"
